### PR TITLE
Evict session in cache when encountering AllNodesFailedException

### LINKED ISSUE #2246: CQLSessionCache: Failure to evict stale sessions on `AllNodesFailedException` prevents automatic recovery from cluster restarts
# TL;DR

- **What’s Broken**: The Data API does not automatically recover after a rapid rolling restart or full cluster restart of Cassandra, leading to permanent `AllNodesFailedException` 500 errors.

- **Why It Breaks (A Two-Part Failure):**
  - **Driver State Failure**: If the Cassandra cluster topology changes too quickly, the driver’s internal map of node IPs becomes completely stale. This happens when the driver loses its connection to all nodes it currently knows about before it has time to learn the new IPs of their replacements. At this point, the CQLSession becomes a “zombie,” as it has no live nodes to query for updated topology information.
  - **DataAPI CQLSession Cache Policy**: The CQLSessionCache has a 5-minute expire-after-access TTL. My testing confirms that **API command traffic** (e.g., insertOne) resets this timer, but Kubernetes health checks do not. If commands are continuously sent to the API while the CQLSession is in this zombie state, the session’s TTL will be perpetually extended, preventing recovery. Recovery only occurs if there is a 5+ minute gap in command traffic, allowing the zombie session to expire naturally.

- **How to Fix It:** We may need the code change in the Data API by catching `AllNodesFailedException`, programmatically evicting the broken session from the cache, and allowing the next request to force an immediate and fresh reconnection.

# 1. Problem Description
The Data API experiences permanent connection failures when Cassandra cluster pods are recycled in Kubernetes. This results in `AllNodesFailedException` 500 errors. The core issue is that under certain restart scenarios, the driver’s internal knowledge of the cluster’s nodes (its topology map) becomes entirely outdated, and it has no mechanism to recover within the existing session. Manual intervention (restarting the Data API pod or waiting for a 5+ minute period of inactivity) is required to restore service.

# 2. Investigation and Tests Performed

A series of methodical tests were conducted to isolate the precise failure conditions:

1. **Full Cluster Restart**: Simultaneously deleting all Cassandra pods reliably reproduced the `AllNodesFailedException`, confirming the Data API does not recover if all nodes disappear at once.
2. **Driver & JVM Configuration Fixes**: I tested two key configuration changes intended to solve caching issues, neither of which resolved the problem.
    - **Driver `advanced.resolve-contact-points`**: Setting `advanced.resolve-contact-points = true/false` in the driver config was tested. This did not work because the setting only applies during the initial bootstrap of a session. Once the driver performs topology discovery, it no longer re-resolves the original DNS name, rendering this setting ineffective for recovery.
    - **JVM DNS Cache**: Applying the JVM argument `-Dsun.net.inetaddr.ttl=10` to the Data API pod also had no effect. This proved the issue was not a simple DNS caching problem, as the driver was no longer performing DNS lookups after establishing its initial connection.
3. **Slow Rolling Restart**: Patiently restarting each Cassandra pod one-by-one, with significant pauses in between, **did not cause a failure**. This demonstrated that if the driver has enough time and at least one stable node, its gossip-based topology discovery works as designed.
4. **Fast Rolling Restart**: Restarting the nodes sequentially but quickly (before the driver could fully stabilize its Control Connection and learn new topology) **did cause the failure**. This pinpointed the failure condition to a rapid, complete invalidation of the driver’s known hosts.
5. **Cache Expiration Test**: After triggering the `AllNodesFailedException` by restarting all pods simultaneously, I waited more than 5 minutes without sending any API commands. A subsequent command then succeeded. This test definitively proved: (a) the session cache does have a working TTL, (b) Kubernetes health checks do not count as “access” to reset the session’s TTL, and (c) creating a new CQLSession can solve the problem.

# 3. Key Findings & Lessons Learned
The combined tests provide a picture of the failure mechanism:
- **The Root Cause is a Stale Topology Map**: The problem is triggered when the driver’s internal topology map becomes 100% stale. This can happen in two primary scenarios:
  - A full cluster restart where all nodes disappear simultaneously.
  - A rolling restart that proceeds too quickly for the driver’s Control Connection to failover and receive gossip updates about the new node IPs before it loses contact with all of its previously known nodes.
- **The Zombie Session**: Once the driver’s map contains no reachable nodes, the CQLSession object enters a “zombie” state. It cannot recover on its own because it has no live connection through which to re-discover the cluster.
- **The Cache Trap in the DataAPI**: The CQLSessionCache’s 5-minute expire-after-access TTL creates a trap. If an application or user continues to send commands while the session is a zombie, each attempt fails but also resets the 5-minute expiration timer. This keeps the broken session in the cache indefinitely, preventing automatic recovery. The system only self-heals if there is a 5+ minute pause in API command traffic.

# 4. Proposed Solution
Implement a code change in the Data API’s `CQLSessionCache`
1. **Catch the Exception**: The code that executes queries should specifically catch `AllNodesFailedException`.
2. **Invalidate and Evict the Zombie Session**: This exception should be treated as a definitive signal that the cached CQLSession is unrecoverable. The cache should immediately invalidate the session and remove the listeners
3. **Enable Immediate Recovery**: With the zombie session evicted, the very next API request for that tenant (even if it arrives milliseconds later) will trigger the creation of a new session. This forces the driver to re-run its bootstrap process, perform a fresh DNS lookup, and successfully connect to the now-available Cassandra cluster, restoring service instantly.

### PR DESCRIPTION
**Pull request by Hazel-Datastax**
**What this PR does**:
Evict session in cache when encountering AllNodesFailedException

**Which issue(s) this PR fixes**:
Fixes #2246

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/exception/APIException.java [hunk 1]
```diff
@@ -97,11 +106,22 @@ public APIException(ErrorInstance errorInstance) {
     this.body = errorInstance.body();
     Objects.requireNonNull(errorInstance.httpStatusOverride(), "httpStatusOverride cannot be null");
     this.httpStatus = errorInstance.httpStatusOverride().orElse(DEFAULT_HTTP_STATUS);
+    Objects.requireNonNull(errorInstance.exceptionActions(), "exceptionActions cannot be null");
+    this.exceptionActions = errorInstance.exceptionActions();
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/APIException.java]: I think you can combine this like:

   this.exceptionActions = Objects.requireNonNull(errorInstance.exceptionActions(), "....");

File: src/main/java/io/stargate/sgv2/jsonapi/exception/APIException.java [hunk 2]
```diff
@@ -97,11 +106,22 @@ public APIException(ErrorInstance errorInstance) {
...
   }
 
   public APIException(
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/APIException.java]: I know Javadoc comment was already missing, but if this is just for testing, maybe add a comment stating that? Otherwise it seems odd to have delegation working in this direction (from individual arguments to wrapper object)

**Review by tatu-at-datastax — APPROVED** [review]
LGTM: had a few questions but seems legit.

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorTemplate.java [hunk 3]
```diff
@@ -56,7 +54,8 @@ public record ErrorTemplate<T extends APIException>(
     String code,
     String title,
     String messageTemplate,
-    Optional<Integer> httpStatusOverride) {
+    Optional<Integer> httpStatusOverride,
+    EnumSet<ExceptionAction> exceptionActions) {
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorTemplate.java]: rename exceptionFlags

and see below, how should these flags be used differenttly to the ones passed in toException ?

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ExceptionAction.java [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+ *
+ * <p>These actions are populated by the code that creates the exception (for example {@link
+ * io.stargate.sgv2.jsonapi.service.cqldriver.executor.DefaultDriverExceptionHandler}) and
+ * interpreted when the exception is mapped to a response. This keeps remediation logic close to
+ * where the error originates while still allowing generic handling at the API layer.
+ *
+ * @see io.stargate.sgv2.jsonapi.service.processor.CommandProcessor#handleExceptionActions
+ * @see io.stargate.sgv2.jsonapi.service.cqldriver.executor.DefaultDriverExceptionHandler
+ */
+public enum ExceptionAction {
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ExceptionAction.java]: rename to ExceptionFlags

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ExceptionAction.java [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+  /**
+   * Evict the session from cache. This is intended for use in scenarios where a session is known to
+   * be in an unrecoverable state (e.g., after all cluster nodes restart) and needs to be forcibly
+   * removed to allow for a fresh connection on the next request.
+   */
+  EVICT_SESSION_CACHE,
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ExceptionAction.java]: nit: lets tweak the name, currently the name and the comments talk about what the outcome we want not the thing that has happened. 

e.g.. 

UNRELIABLE_DB_SESSION - the error indicates that the DB session used is no longer reliable and should be terminated

File: src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/CQLSessionCache.java [hunk 6]
```diff
@@ -213,6 +213,46 @@ public CqlSession getSession(String tenantId, String authToken, String userAgent
...
+   * @param userAgent Nullable user agent
+   * @return {@code true} if a session was evicted, {@code false} otherwise.
+   */
+  public boolean evictSession(String tenantId, String authToken, String userAgent) {
+
+    var cacheKey = createCacheKey(tenantId, authToken, userAgent);
+
+    // Invalidate the key. This will trigger the onKeyRemoved listener,
+    // which will close the CqlSession and run other cleanup.
+    if (sessionCache.asMap().remove(cacheKey) != null) {
```
[the remark this answers is not in the document]
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/CQLSessionCache.java]: +1 and you can link to the stack overflow thread for why

**Review by amorton — CHANGES_REQUESTED** [review]

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCode.java [hunk 7]
```diff
@@ -67,6 +77,10 @@ default T get(Map<String, String> values) {
     return template().toException(values);
   }
 
+  default T get(EnumSet<ExceptionFlags> exceptionFlags, Map<String, String> values) {
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCode.java]: nit: have `get(Map<String, String> values)` call this overload

File: src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/DefaultDriverExceptionHandler.java [hunk 8]
```diff
@@ -162,7 +165,8 @@ public RuntimeException handle(AllNodesFailedException exception) {
       case DriverException e -> maybeHandle(e);
         // this is a non-driver based exception, so map to generic unexpected driver error
       case RuntimeException re ->
-          DatabaseException.Code.UNEXPECTED_DRIVER_ERROR.get(errVars(schemaObject, re));
+          DatabaseException.Code.UNEXPECTED_DRIVER_ERROR.get(
+              EnumSet.of(UNRELIABLE_DB_SESSION), errVars(schemaObject, re));
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/DefaultDriverExceptionHandler.java]: mmmm, not sure but I dont think it will hurt anything too much

File: src/test/java/io/stargate/sgv2/jsonapi/exception/APIExceptionTest.java [hunk 9]
```diff
@@ -71,4 +72,42 @@ public void toStringFormatted() {
         .contains(exception.title)
         .contains(exception.body);
   }
+
+  @Test
+  public void defaultExceptionActionsFieldEmpty() {
```
Comment (amorton) [inline src/test/java/io/stargate/sgv2/jsonapi/exception/APIExceptionTest.java]: nit: defaultExceptionActionsFieldEmpty to defaultExceptionFlagsFieldEmpty

**Review by amorton — APPROVED** [review]
looks good, some nit picks otherwise ship it
