### PR TITLE
Fix unhandled errors when create table with unsupported API data types

### LINKED ISSUE #1917: `SERVER_UNHANDLED_ERROR` for `createTable` due to unsupported data type?
From Splunk I see (via https://datastax.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dastra_dataplane_prod%20cloud.accountID%3D551367681185%20k8s-container_name%3Djsonapi%20SERVER_UNHANDLED_ERROR%20UnsupportedUserApiDataType%20%7C%20sort%20-_time%20%7C%20table%20_time%2C%20k8s-pod_name%2C%20level%2C%20mdc.tenantId%2C%20message%7B%7D&earliest=1741771325&latest=1741792925&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=&display.page.search.tab=statistics&display.general.type=statistics&sid=1741793635.247163 )

thousands of entries like:

```
{"commandName":"CreateTableCommand","tenant":"4e1205c7-6cf6-49d7-bd71-f43f7a578cfd","namespaceName":"default_keyspace","collectionName":"","schemaType":"KEYSPACE","documentsReceived":"NA","documentsReturned":"NA","errorList":[{"message":"Server failed: root cause: (java.lang.UnsupportedOperationException) UnsupportedUserApiDataType does not have getCqlType","errorCode":"SERVER_UNHANDLED_ERROR","id":"c1efbce6-3bf1-41ef-9e87-bf357c6577f8","family":"SERVER","title":"Server failed","scope":"DATABASE"}]}
```

so looks like something in internal processing is not handling unsupported data type (type not obvious from message) well, resulting in (I think) 500 being returned to caller.

### PR DESCRIPTION
**Pull request by Yuqi-Du**
- fixes issue #1917
- What we did for filtering target columnDef in ApiColumnDefContainer is not clear and mostly redundant. This PR refactors the flow, and refines how we do filtering.

Resolves bunch of TODOs:
```
'previously'

   var matcher =
        ApiSupportDef.Matcher.NO_MATCHES.withCreateTable(true).withInsert(true).withRead(true);
    var vectorColumnDefs =
        apiTableDef
            .allColumns()
            .filterBySupport(matcher)
            .filterByApiTypeNameToList(ApiTypeName.VECTOR);

'now'

    var vectorColumnDefs = apiTableDef.allColumns().filterVectorColumnsToList();
```

**Which issue(s) this PR fixes**:
Fixes #1917

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/schema/tables/ApiDataTypeDefs.java [hunk 1]
```diff
@@ -107,4 +108,9 @@ public abstract class ApiDataTypeDefs {
       List.of(
           ASCII, BIGINT, BOOLEAN, BINARY, COUNTER, DATE, DECIMAL, DOUBLE, DURATION, FLOAT, INT,
           SMALLINT, TEXT, TIME, TIMESTAMP, TINYINT, VARINT, INET, UUID, TIMEUUID);
+
+  public static List<PrimitiveApiDataTypeDef> filterBySupportToList(
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/service/schema/tables/ApiDataTypeDefs.java:112]: nit: doc comment pls

**Review by amorton — APPROVED** [review]
look good - but needs to add checking in alterTable when addColumn is used

File: src/main/java/io/stargate/sgv2/jsonapi/service/schema/tables/ApiDataTypeDefs.java (hunk 1 above)
Comment (Yuqi-Du) [reply src/main/java/io/stargate/sgv2/jsonapi/service/schema/tables/ApiDataTypeDefs.java:112]: added

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/CreateTableCommandResolver.java [hunk 2]
```diff
@@ -59,6 +64,28 @@ public Operation<KeyspaceSchemaObject> resolveKeyspaceCommand(
     var apiTableDef =
         ApiTableDef.FROM_TABLE_DESC_FACTORY.create(
             tableName, command.definition(), validateVectorize);
+
+    var unsupportedColumnsCreateTable =
```
[the remark this answers is not in the document]
Comment (Yuqi-Du) [reply src/main/java/io/stargate/sgv2/jsonapi/service/resolver/CreateTableCommandResolver.java:68]: added
