### PR TITLE
Fixes #1332: separate out ErrorCode.VECTOR_SIZE_MISMATCH from INVALID_QUERY

### LINKED ISSUE #1332: Create and use new `ErrorCode` for Vector-size-mismatch case of `INVALID_QUERY`
Currently handling of `QueryValidationException` when caught has one special case: detection of vector size mismatch. But the only thing done there is to use a better error message, `ErrorCode` still uses generic `INVALID_QUERY`.

Let's instead split it off into a new `ErrorCode` to make handling easier via Grafana dashboards; use that code for vector size mismatch.

Note: this is a minimal short-term improvement before full rewrite of error construction, which will add "family", "scope" and other aspects.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Separates out new `ErrorCode`, `VECTOR_SIZE_MISMATCH` out of generic `INVALID_QUERY`; improves message slightly. But mostly helps with metrics dashboard to spell out actual issue.

**Which issue(s) this PR fixes**:
Fixes #1332

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/VectorSearchIntegrationTest.java [hunk 1]
```diff
@@ -985,7 +985,7 @@ public void failWithEmptyVector() {
     }
 
     @Test
-    @Order(4)
+    @Order(5)
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/VectorSearchIntegrationTest.java:988]: Had duplicate for `4`, fixing it.

**Review by Yuqi-Du — APPROVED** [review]

**Review by vkarpov15 — COMMENTED** [review]
LGTM
