### PR TITLE
Fix #1812: create new `ErrorCodeV1.INVALID_REQUEST_BAD_SYNTAX`, map non-parsing errors to that

### LINKED ISSUE #1812: Invalid createIndex structure causes "Request invalid, cannot parse as JSON" error even though request is valid JSON
When sending the following `createIndex` command to Data API v1.0.20:

```
{
  "createIndex": {
    "name": {
      "name": 1
    },
    "definition": {
      "column": {
        "background": true
      },
      "options": {}
    },
    "options": {}
  }
}
```

I get back the following error:

```
HTTP error (400): {"errors":[{"message":"Request invalid, cannot parse as JSON: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)\n at [Source: (ByteArrayInputStream); line: 1, column: 24] (through reference chain: io.stargate.sgv2.jsonapi.api.model.command.impl.CreateIndexCommand[\"name\"])","errorCode":"INVALID_REQUEST_NOT_JSON","id":"4353e100-2914-4af1-85da-7ed6739999f6","family":"REQUEST","title":"Request invalid, cannot parse as JSON","scope":"EMPTY"}]}
```

Admittedly the error message does contain "Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)", which is more correct (`name` should be string not object), but the "cannot parse as JSON" error title is misleading because the request is valid JSON, just not correct command syntax.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Improves error handling wrt #1812

**Which issue(s) this PR fixes**:
Fixes #1812

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/table/definition/TableDefinitionDesc.java [hunk 1]
```diff
@@ -14,8 +13,6 @@
  *
  * <p>Has the columns and the primary key definition, not the name of the table.
  */
-@JsonPropertyOrder({"name", "definition"})
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/table/definition/TableDefinitionDesc.java:17]: Not needed as we are not serializing these definitions (but if we did, had wrong column names :) ).

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java [hunk 2]
```diff
@@ -47,6 +47,8 @@ public enum ErrorCodeV1 {
   /** note: Only used by EmbeddingGateway */
   INVALID_REQUEST("Request not supported by the data store"),
 
+  INVALID_REQUEST_BAD_SYNTAX("Request invalid, JSON syntax incorrect"),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java:50]: Adding as old-style error code for minimal change right now, since code is called by `ThrowableToErrorMapper` with limited access.

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/CreateTableIntegrationTest.java [hunk 3]
```diff
@@ -322,10 +322,10 @@ private static Stream<Arguments> allTableData() {
                           """,
                   "invalidPartitionSortOrderingValueTable",
                   true,
-                  ErrorCodeV1.INVALID_REQUEST_NOT_JSON.name(),
+                  ErrorCodeV1.INVALID_REQUEST_BAD_SYNTAX.name(),
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/CreateTableIntegrationTest.java:325]: Gee, figuring out how to fix this test was not easy: not a big fan of huge matrix tests because IDE makes it difficult to find out where the actual test data originates in. :-(

**Review by Hazel-Datastax — APPROVED** [review]
LGTM.

I saw your question in the [issue](https://github.com/stargate/data-api/issues/1812) - whether to change HTTP response code from 400 to 200. Good question, both 400 and 200 would make sense to me but I personally think maybe 200 is better, since most errors are 200 and “bad json syntax” sounds more like the user doesn’t follow our definition.

Want to hear others’ thoughts

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/CreateTableIndexIntegrationTest.java [hunk 4]
```diff
@@ -483,6 +485,31 @@ public void createIndexWithUnknownIndexType() {
...
+                            "definition": {
+                              "column": {
+                                "background": true
+                              },
+                            }
+                        }
+                        """)
+          .hasSingleApiError(
+              ErrorCodeV1.INVALID_REQUEST_BAD_SYNTAX,
+              "Request invalid, JSON syntax incorrect: underlying problem");
```
Comment (vkarpov15) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/CreateTableIndexIntegrationTest.java:511]: I'm not a fan of the "JSON syntax incorrect" bit because that implies that the request is invalid JSON, which isn't true. I would recommend changing to "invalid Data API request syntax" or something similar to imply that the JSON itself is valid, just the command syntax is not correct.

Comment (tatu-at-datastax) [reply src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/CreateTableIndexIntegrationTest.java:511]: Fundamentally it is not valid message, structurally. Maybe "mismatching"?

"mismatching JSON structure"?

I am looking for better wording and open to suggestions.

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java [hunk 5]
```diff
@@ -47,6 +47,8 @@ public enum ErrorCodeV1 {
   /** note: Only used by EmbeddingGateway */
   INVALID_REQUEST("Request not supported by the data store"),
 
+  INVALID_REQUEST_STRUCTURE_MISMATCH("Request invalid, mismatching JSON structure"),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java:50]: @vkarpov15 Changed error code, wording, is this any closer to being acceptable? I am happy to keep on tweaking it until we get it right.

Comment (vkarpov15) [reply src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java:50]: I think this message is good enough, thanks for listening :+1:
