### PR TITLE
Fix #2164: Map<K, Boolean> into Map<K, String> + post-process for config handling

### LINKED ISSUE #2164: Change to fix breaking Quarkus config (SmallRye): "" no longer acceptable as `null` for `Boolean`
Looks like something in SmallRye config library broke such that our use of "" for "undefined" (`null`) for `ApiFeature` throws exception.

This is pretty nasty regression, but not much we can do except to use `Optional<Boolean>` instead of `Boolean`.

**EDIT**: Change to use `Optional<Boolean>` does NOT WORK as value of `Map`: `Map<ApiType, Optional<Boolean>>` fails!!!

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Uses `Map<ApiFeature, String>` instead of `Map<ApiFeature, Boolean>` for configuration, with bit of post-processing.

**Which issue(s) this PR fixes**:
Fixes #2164

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Third attempt: bind to `Map<ApiFeature, String>` at first: this SHOULD work.
And then finagle into `Boolean` manually.

File: src/main/java/io/stargate/sgv2/jsonapi/config/feature/ApiFeatures.java [hunk 1]
```diff
@@ -51,4 +51,18 @@ public boolean isFeatureEnabled(ApiFeature flag) {
     }
     return flag.enabledByDefault();
   }
+
+  private Boolean booleanFromString(String str) {
+    if (str == null || str.isBlank()) {
+      return null; // no value, so not enabled
+    }
+    if ("true".equals(str)) {
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/config/feature/ApiFeatures.java:60]: should this be `equalsIgnoreCase()`

**Review by amorton — APPROVED** [review]
Approved so it can merge, but checking should it be equalsIgnoreCase()

File: src/main/java/io/stargate/sgv2/jsonapi/config/feature/ApiFeatures.java (hunk 1 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/config/feature/ApiFeatures.java:60]: Matter of taste: I think by default only "true" and "false" accepted for boolean/Boolean in Java.

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/RerankFeatureDisabledIntegrationTest.java [hunk 2]
```diff
@@ -30,9 +30,10 @@ public TestResource() {}
 
     @Override
     public String getFeatureFlagReranking() {
-      // return empty to leave feature "undefined" (disabled unless per-request header override)
+      // return BLANK String to leave feature "undefined" (disabled unless per-request header
+      // override)
       // ("false" would be "disabled" for all tests, regardless of headers)
-      return "";
+      return " ";
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/RerankFeatureDisabledIntegrationTest.java:36]: Using non-empty because apparently SmallRye fails on Empty String directly. What a piece-of-work library :-(
