### PR TITLE
Fix #1950: prevent use of operators like $push on $lexical field

### LINKED ISSUE #1950: Lexical: check argument types for $set, $unset operations; check no other operations allowed on `$lexical`
(follow-up to #1941 )

We should check that:

1. Argument for `$set` on `$lexical` is either STRING or NULL: fail otherwise
2. No operations other than `$set` and `$unset` are allowed on `$lexical`

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds check to prevent use of operators other than `$set`, `$unset`, `$setOnInsert` for new `$lexical` field -- similar to blocks for `$vector` and `$vectorize`.
Also cleans up error reporting code slightly.

**Which issue(s) this PR fixes**:
Fixes #1950

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java [hunk 1]
```diff
@@ -138,14 +138,14 @@ public enum ErrorCodeV1 {
 
   UNSUPPORTED_UPDATE_OPERATION_PARAM("Unsupported update operation parameter"),
 
-  UNSUPPORTED_UPDATE_OPERATION_PATH("Invalid update operation path"),
+  UNSUPPORTED_UPDATE_OPERATION_PATH("Unsupported update operation path"),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java:141]: To match error code.

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java [hunk 2]
```diff
@@ -138,14 +138,14 @@ public enum ErrorCodeV1 {
...
 
   UNSUPPORTED_UPDATE_OPERATION_TARGET("Unsupported target JSON value for update operation"),
 
-  UNSUPPORTED_UPDATE_FOR_DOC_ID("Cannot use operator with '_id' property"),
-
-  UNSUPPORTED_UPDATE_FOR_VECTOR("Cannot use operator with '$vector' property"),
-  UNSUPPORTED_UPDATE_FOR_VECTORIZE("Cannot use operator with '$vectorize' property"),
+  UNSUPPORTED_UPDATE_FOR_DOC_ID("Cannot use operator with '_id' field"),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java:145]: To align terminology ("fields" for Documents; "columns" for Tables)

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/FindOneAndUpdateIntegrationTest.java [hunk 3]
```diff
@@ -55,14 +55,7 @@ public void byIdAndSet() {
             }
           }
           """;
-      given()
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/FindOneAndUpdateIntegrationTest.java:58]: Mechanical changes to reduce verbosity; about 20% fewer lines.

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/UpdateOneWithLexicalCollectionIntegrationTest.java [hunk 4]
```diff
@@ -275,6 +277,71 @@ public void unsetOneToRemoveFromResults() {
...
 
+  /**
+   * Tests to ensure only allowed operations for $lexical are $set and $unset, rest are not allowed.
+   * Will not do exhaustive coverage, just spot checks.
+   */
+  @DisabledIfSystemProperty(named = TEST_PROP_LEXICAL_DISABLED, matches = "true")
+  @Nested
+  @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
+  @Order(10)
+  class NotAllowedOperations {
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/UpdateOneWithLexicalCollectionIntegrationTest.java:288]: Actual main tests of this PR.

**Review by Yuqi-Du — APPROVED** [review]
neat! approved.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/clause/update/UpdateOperation.java [hunk 5]
```diff
@@ -50,22 +50,33 @@ public boolean shouldApplyIf(boolean isInsert) {
...
-            || oper.apiName().equals("$unset")
-            || oper.apiName().equals("$setOnInsert"))) {
-      throw ErrorCodeV1.UNSUPPORTED_UPDATE_FOR_VECTORIZE.toApiException("%s", oper.apiName());
-    }
-
-    if (DocumentConstants.Fields.DOC_ID.equals(path)) {
-      throw ErrorCodeV1.UNSUPPORTED_UPDATE_FOR_DOC_ID.toApiException("%s", oper.apiName());
+    switch (path) {
+      case DocumentConstants.Fields.VECTOR_EMBEDDING_FIELD:
+        switch (oper.apiName()) {
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/clause/update/UpdateOperation.java:55]: -1 oper is an ENUM can we use the enum values rather than constants

File: src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java (hunk 2 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCodeV1.java:145]: can we please stop adding more v1 errors ... this should be in the V2 errors file UNSUPPORTED_UPDATE_FOR_LEXICAL

**Review by amorton — APPROVED** [review]
-1 for using string constants rather than the enum , but otherwise approved

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/clause/update/UpdateOperation.java (hunk 5 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/clause/update/UpdateOperation.java:55]: Ah good point. Was blindly converting existing code. Will change.
