### PR TITLE
Fix #2318 collections to use DefaultDriverExceptionHandler

### LINKED ISSUE #2318: Update Collection driver code to use V2 errors and DriverExceptionHandler
As part of removing the V1 errors, update all collection code so when it is working with the driver it uses the DriverExceptionHandler structure 
so any errors from the driver can have the same handling for tables and collections.

### PR DESCRIPTION
**Pull request by amorton**
Updates the collection code to use the `DefaultDriverExceptionHandler` like the tables, and improves the `CommandErrorV2` use so all API public errors are created the same way 

**Which issue(s) this PR fixes**:
Fixes #2318 

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandErrorV2.java [hunk 1]
```diff
@@ -1,152 +1,153 @@
...
+  private static String requireNoNullOrBlank(String value, String message) {
+    if (Objects.isNull(value) || value.isBlank()) {
+      throw new IllegalArgumentException(message);
+    }
+    return value;
   }
 
-  public String getTitle() {
-    return title;
+  // XXX TO COMMENT
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandErrorV2.java]: Add the comment? :)

Esp. since I am not quite sure what the logic is wrt "identity" in this case: was about to suggest implementation on top of `equals()` but that's not what is being done here.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandResultBuilder.java [hunk 2]
```diff
@@ -37,22 +35,19 @@ public enum ResponseType {
   private final ResponseType responseType;
 
   private final RequestTracing requestTracing;
-  // Created in the Ctor
-  private final APIExceptionCommandErrorBuilder apiExceptionToError;
 
-  // another builder, because if we add a warning we want to use the V2 error object
-  // but may not be returning V2 errors in the result
-  private final APIExceptionCommandErrorBuilder apiWarningToError;
+  // amorton - we could probably use the same factory for errors and warning, keeping seperate
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandResultBuilder.java]: typo: seperate -> separate

File: src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/GenericExceptionMapper.java [hunk 3]
```diff
@@ -1,26 +1,20 @@
...
-    JsonParseException.class,
-    MismatchedInputException.class
-  })
-  public RestResponse<CommandResult> genericExceptionMapper(Throwable e) {
-
-    CommandResult commandResult = new ThrowableCommandResultSupplier(e).get();
-    return commandResult.toRestResponse();
-  }
-}
+// public class GenericExceptionMapper {
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/GenericExceptionMapper.java]: delete the file

File: src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java [hunk 4]
```diff
@@ -1,270 +1,286 @@
...
 
 /**
- * Simple mapper for mapping {@link Throwable}s to {@link CommandResult.Error}, with a default
- * implementation.
+ * amorton - 7 jan 2026 refactor NOTES: leaving this named ThrowableToErrorMapper because we know it
+ * as that name.
+ *
+ * <p>Changed the role to ONLY be remaping Java exception to exception. Previously it would also
+ * build the Command error (CommandResult.Error) that is returned to the client. Made the change to
+ * try simplifying as I work to remove this class completly.
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java]: typo: completly -> completely

File: src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/SchemaCache.java [hunk 5]
```diff
@@ -126,6 +126,7 @@ private TableBasedSchemaCache onLoad(SchemaCache.KeyspaceCacheKey key) {
     // Cannot get a session from the sessionCacheSupplier in the constructor because
     // it will create a circular call. So need to wait until now to create the QueryExecutor
     // this is OK, only happens when the table is not in the cache
+    // HACK - fix before merge
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/SchemaCache.java]: hmmm?

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 6]
```diff
@@ -318,14 +319,26 @@ private Uni<Supplier<CommandResult>> executeCollectionCreation(
...
-                    "provided collection ('%s')", name);
+                // HACK - remove when re-writing this class
+                return commandResultSupplier(
+                    DatabaseException.Code.CORRUPTED_COLLECTION_SCHEMA.get(
+                        errVars(
+                            commandContext.schemaObject(),
+                            map ->
+                                map.put(
+                                    "errorMessage",
+                                    "Collection creation failure (unable to create table)."))));
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java]: nit: usually trailing period part of template, not substitution part.

**Review by tatu-at-datastax — APPROVED** [review]
LGTM: a few nits, typos, questions.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandError.java [hunk 7]
```diff
@@ -1,84 +0,0 @@
...
- *
- * <p>This object is intended to be used in the CommandResult, and is serialised into the JSON
- * response.
- *
- * <p>aaron - 9 -oct-2024 - This is initially only used with the Warnings in the CommandResult,
- * further work needed to use it in all places. Warnings are in the status, and not described on the
- * swagger for the CommandResult. This is why all the decorators from the original class are not
- * here yet, but they have things to ignore flagged just incase
- */
-public class CommandError {
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandError.java]: all in CommandErrorV2 now

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandResultBuilder.java (hunk 2 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandResultBuilder.java]: :)

File: src/main/java/io/stargate/sgv2/jsonapi/config/DebugConfigAccess.java [hunk 8]
```diff
@@ -24,4 +24,31 @@ public static boolean isDebugEnabled() {
   public static void setDebugEnabled(boolean state) {
     debugEnabled = state;
   }
+
+  /**
+   * Enables debug for the duration of a try-with-resources block.
```
[the remark this answers is not in the document]
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/config/DebugConfigAccess.java]: There are tests that check if the exceptionClass is in the response, and they were setting this manually, or after I made some changes it was needed to make sure it was reset . I think we should remove the error class from response so may be removable at that time

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandErrorFactory.java [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+        .metricsTags(ExceptionMetrics.tagsFor(jsonApiException))
+        .family(jsonApiException.getErrorFamily().toString())
+        .scope(jsonApiException.getErrorScope().toString())
+        .title(jsonApiException.getTitle())
+        .id(jsonApiException.getErrorId())
+        .documentIds(documentIds == null ? Collections.emptyList() : documentIds)
+        .build();
+  }
+
+  public CommandErrorV2 create(APIException apiException) {
```
[the remark this answers is not in the document]
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandErrorFactory.java]: Will chat next time, I added this because in the Uni callbacks we get a `Throwable` type var even if the runtime instance is the ApiException, so this was to find the appropriate overload at run time

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandErrorV2.java [hunk 10]
```diff
@@ -1,152 +1,153 @@
...
-                  metricsTags,
-                  family,
-                  scope,
-                  title,
-                  id));
+    public Builder documentIds(List<? extends DocRowIdentifer> documentIds) {
+      this.documentIds =
+          documentIds == null
+              ? Collections.emptyList()
+              : documentIds.stream().map(d -> (DocRowIdentifer) d).toList();
```
[the remark this answers is not in the document]
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandErrorV2.java]: Yes, both defensive copy and to do the generics dance from wild card.
