### PR TITLE
Fix #1287: convert internal assertion exceptions to use JsonApiException.SERVER_INTERNAL_ERROR

### LINKED ISSUE #1287: Convert internal "assert"-style `RuntimeException` into `JsonApiException` with `ErrorCode.SERVER_INTERNAL_ERROR`
There are a few cases of plain `RuntimeException` (and `UnsupportedOperationException`s, `IllegalArgumentException`s, `IllegalStateException`s) thrown to basically assert that something that should never happen, never happens. While we can map these in various places to `JsonApiException`, there seems no real benefit to not just throwing with

    throw ErrorCode.SERVER_INTERNAL_ERROR.toApiException(message); // possibly templated

so let's clean code base; there are about 63 of these all in all and not all need conversion.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Converts most of usage of `RuntimeException` and sub-classes (`IllegalArgumentException`, `UnsupportedOperationException`) to use `JsonApiException` with `ErrorCode.SERVER_INTERNAL_ERROR` for better diagnostics

**Which issue(s) this PR fixes**:
Fixes #1287

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/exception/JsonApiException.java [hunk 1]
```diff
@@ -25,23 +25,24 @@ public class JsonApiException extends RuntimeException implements Supplier<Comma
 
   private final Response.Status httpStatus;
 
-  public JsonApiException(ErrorCode errorCode) {
+  protected JsonApiException(ErrorCode errorCode) {
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/JsonApiException.java:28]: These changes were accidentally missing from PR for #1283

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/collection/AllCollectionFilter.java [hunk 2]
```diff
@@ -66,6 +67,7 @@ public List<BuiltCondition> getAll() {
 
   @Override
   public BuiltCondition get() {
-    throw new UnsupportedOperationException("For $all filter we always use getAll() method");
+    throw ErrorCode.SERVER_INTERNAL_ERROR.toApiException(
+        "For $all filter we always use getAll() method");
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/collection/AllCollectionFilter.java:71]: Memory comes back, if we can not use get() for all filters, that means we need to rethink about the interface design. I will add a todo.

**Review by Yuqi-Du — APPROVED** [review]
