### PR TITLE
Fix #2392: `EmbeddingProvider` and `RerankingProvider` `decideRetry()` buggy

### LINKED ISSUE #2392: `EmbeddingProvider.decideRetry()` and `RerankingProvider.decideRetry()` fail to retry actual timeouts
As things are, `decideRetry()` methods of both provider implementations are wrong as they do not match actual `APIException`s that are mapped.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes logic for determining retries to actually retry timeouts

**Which issue(s) this PR fixes**:
Fixes #2392

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/reranking/operation/RerankingProvider.java [hunk 1]
```diff
@@ -122,11 +122,9 @@ protected int atMostRetries() {
 
   @Override
   protected boolean decideRetry(Throwable throwable) {
-
-    var retry =
-        (throwable.getCause() instanceof SchemaException se
-            && se.code.equals(RerankingProviderException.Code.RERANKING_PROVIDER_TIMEOUT.name()));
-
+    boolean retry =
+        throwable instanceof RerankingProviderException rpe
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/reranking/operation/RerankingProvider.java]: note: remove `getCause()` as exception should not be cause but mapper exception itself.
