### PR TITLE
Fix #1098: prevent NPE for unknown embedding provider id

### LINKED ISSUE #1098: Possible NPE in `EmbeddingProviderFactory` for mismatched/missing embedding provider id
Code in `EmbeddingProviderFactory` assumes that provider id is valid and maps to implementation, calling `create` without null check:

```
    return providersMap
        .get(configuration.serviceProvider())
        .create(...)
```

but it really should validate to avoid NPE if things go wrong (missing provider), give better failure message.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds null checks to avoid NPE.

**Which issue(s) this PR fixes**:
Fixes #1098

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/embedding/operation/EmbeddingProviderFactory.java [hunk 1]
```diff
@@ -96,33 +95,29 @@ private synchronized EmbeddingProvider addService(
...
-              (EmbeddingProvider) clazz.get().getConstructor().newInstance();
-          return customEmbeddingProvider;
-        } else {
-          throw new JsonApiException(
-              ErrorCode.VECTORIZE_SERVICE_TYPE_UNAVAILABLE,
-              ErrorCode.VECTORIZE_SERVICE_TYPE_UNAVAILABLE.getMessage() + "custom class undefined");
-        }
+        return (EmbeddingProvider) clazz.get().getConstructor().newInstance();
       } catch (Exception e) {
-        throw new JsonApiException(
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/embedding/operation/EmbeddingProviderFactory.java:111]: Refactored so that "JsonApiException" just thrown is not caught, wrapped, re-thrown.

**Review by Yuqi-Du — APPROVED** [review]
