### PR TITLE
fixes #1954 improved rerankOn

### LINKED ISSUE #1954: [collections, BYOV, findAndRerank] Bad 500 error from API if rerankOn field contains non-text for some documents
If the collection has a document with something other than a string for the rerankOn field, a FARR command on a nonvectorize collection fails badly with a 500 and:

> Passage field xcontent not a text node in document _id="2". Server error '500 Internal Server Error'

### PR DESCRIPTION
**Pull request by amorton**
(existing) if vectorize was used in findAndRerank we use that query as the query to rerank on, otherwise use rerankOn option

no matter what, when we get the node to rerank on if it is a value node (text, number , etc) we get the text value of it.

if null or empty string or not defined we drop the doc and do not rerank

otherwise (present but array or object) we error

passage extraction is tested in unit tests, see ScoredDocumentTests

# Examples: 

Inserting 

```json
{
    "insertMany": {
        "documents": [
            {
                "_id": 1,
                "$vectorize": "I like cheese",
                "$lexical": "cheese cows milk",
                "name": "Alice",
                "country": "NZ",
                "age": 40,
                "meta" : {
                    "content" : "I like cheese"
                }
            },
            {
                "_id": 2,
                "$vectorize": "I like monkeys",
                "$lexical": "monkeys bananas",
                "name": "Aaron",
                "country": "NZ",
                "age": 50,
                "meta" : {
                    "content" : "I like monkeys"
                }
            },
            {
                "_id": 3,
                "$vectorize": "I have a neutral opinion on both cheese and monkeys",
                "$lexical": "cheese cows milk monkeys bananas",
                "name": "Bob",
                "country": "AUS",
                "age": 60,
                "meta" : {
                    "content" : "I have a neutral opinion on both cheese and monkeys"
                }
            },
            {
                "_id": 4,
                "$lexical": "cheese cows milk monkeys bananas",
                "name": "Charlie - no vector",
                "country": "AUS",
                "age": 70,
                "meta" : {
                    "content" : 1
                }
            }
        ]
    }
}
```

Reading, not passing a vector, using rerankOn, and the rerankOn value for doc 4 is an integer 

```json
{
    "findAndRerank": {
        "filter": {},
        "projection": {
            "_id": 1,
            "name": 1,
            "$vectorize": 1,
            "meta": 1
        },
        "sort": {
            "$hybrid": {
                "$lexical": "monkeys",
                "$vector": [
                    0.030776024,
                    
                    0.008515012
                ]
            }
        },
        "options": {
            "rerankQuery": "I like cheese",
            "rerankOn": "meta.content",
            "limit": 10,
            "hybridLimits" : {
                "$lexical" : 10,
                "$vector" : 14
            },
            "includeScores": true,
            "includeSortVector": false
        }
    }
}
```

Returns: 
Includes doc 4 , even though it was ranked 2 by BMM the Reranker put it last 

```json
{
    "data": {
        "documents": [
            {
                "_id": 1,
                "$vectorize": "I like cheese",
                "name": "Alice",
                "meta": {
                    "content": "I like cheese"
                }
            },
            {
                "_id": 3,
                "$vectorize": "I have a neutral opinion on both cheese and monkeys",
                "name": "Bob",
                "meta": {
                    "content": "I have a neutral opinion on both cheese and monkeys"
                }
            },
            {
                "_id": 2,
                "$vectorize": "I like monkeys",
                "name": "Aaron",
                "meta": {
                    "content": "I like monkeys"
                }
            },
            {
                "_id": 4,
                "name": "Charlie - no vector",
                "meta": {
                    "content": 1
                }
            }
        ],
        "nextPageState": null
    },
    "status": {
"documentResponses": [
            {
                "scores": {
                    "$rerank": 9.1015625,
                    "$vector": 0.7426339,
                    "$vectorRank": 3,
                    "$bm25Rank": null,
                    "$rrf": 0.015873017
                }
            },
            {
                "scores": {
                    "$rerank": 1.0664062,
                    "$vector": 0.8216057,
                    "$vectorRank": 2,
                    "$bm25Rank": 3,
                    "$rrf": 0.032002047
                }
            },
            {
                "scores": {
                    "$rerank": -5.6875,
                    "$vector": 1.0,
                    "$vectorRank": 1,
                    "$bm25Rank": 1,
                    "$rrf": 0.032786883
                }
            },
            {
                "scores": {
                    "$rerank": -7.9648438,
                    "$vector": -2.1474836E9,
                    "$vectorRank": null,
                    "$bm25Rank": 2,
                    "$rrf": 0.016129032
                }
            }
        ]
    }
}
```

Tracing shows the rerank passage for doc 4 was "1", text value of it's numeric node value for `meta.content`

```json
 {
    "TraceEvent": {
        "eventId": "01961281-f240-73c5-b6d1-b7da1e8a5b84",
        "timestamp": "2025-04-07T23:07:08.224896Z",
        "elapsedMicroseconds": 375373.0,
        "message": "De-duplicated for reranking, reads=2, total documents=6, dropped documents=0, deduplicated documents=4",
        "data": null
    }
},
{
    "TraceEvent": {
        "eventId": "01961281-f241-7ed0-b6ce-c13cc8026618",
        "timestamp": "2025-04-07T23:07:08.225159Z",
        "elapsedMicroseconds": 375640.0,
        "message": "Reranking 4 passages using NvidiaRerankingProvider with model nvidia/llama-3.2-nv-rerankqa-1b-v2",
        "data": {
            "RecordableMap": {
                "limit": 10.0,
                "passages": [
                    "I like cheese",
                    "I like monkeys",
                    "I have a neutral opinion on both cheese and monkeys",
                    "1"
                ],
                "query": "I like cheese"
            }
        }
    }
},
{
    "TraceEvent": {
        "eventId": "01961281-f474-700e-a28b-fad927ef2bd4",
        "timestamp": "2025-04-07T23:07:08.788997Z",
        "elapsedMicroseconds": 939481.0,
        "message": "Processing reranking response with 4 scores using NvidiaRerankingProvider with model nvidia/llama-3.2-nv-rerankqa-1b-v2",
        "data": {
            "RecordableMap": {
                "scores": [
                    "Rank[index=0, score=9.1015625]",
                    "Rank[index=1, score=-5.6875]",
                    "Rank[index=2, score=1.0664062]",
                    "Rank[index=3, score=-7.9648438]"
                ]
            }
        }
    }
},
```

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #1954

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java [hunk 1]
```diff
@@ -149,26 +149,33 @@ float[] sortVector() {
...
       int droppedDocuments,
       List<ScoredDocument> deduplicatedDocuments) {}
 
-  private DeduplicationResult deduplicateResults(List<CommandResult> rawReadResults) {
+  private DeduplicationResult deduplicateResults() {
 
-    if (rawReadResults.isEmpty()) {
-      throw new IllegalArgumentException("rawReadResults must not be empty");
+    if (deferredReads.isEmpty()) {
+      throw new IllegalArgumentException("deferredReads must not be empty");
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java:164]: nit: since deferredReads is not an argument, better choice might be `IllegalStateException`.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java [hunk 2]
```diff
@@ -149,26 +149,33 @@ float[] sortVector() {
...
-    // Keyed on the _id as a JsonNode
-
     ScoredDocumentMerger merger = null;
     int totalReads = 0;
 
-    for (var commandResult : rawReadResults) {
+    for (var deferredAndSource : deferredReads) {
+      var commandResult =
+          Objects.requireNonNull(
+              deferredAndSource.deferredRead().commandResult(),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java:175]: Not the biggest problem in the world but I think this will eagerly construct error String that is almost never needed.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java [hunk 3]
```diff
@@ -14,22 +28,26 @@ public class ScoredDocument implements Comparable<ScoredDocument> {
...
+  @VisibleForTesting
+  protected ScoredDocument(JsonNode id, JsonNode document, String passage, DocumentScores scores) {
     this(id, checkCast(document), passage, scores);
   }
 
   private static ObjectNode checkCast(JsonNode document) {
     if (document instanceof ObjectNode on) {
       return on;
     }
+    Objects.requireNonNull(document, "document cannot be null");
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java:44]: I guess it's nicer in (very) unlikely case of getting non-ObjectNode, but simple 1-line cast would also work -- in rare fail case `ClassCastException` from specific line is easy to find. :-)

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java [hunk 4]
```diff
@@ -38,16 +56,101 @@ private static ObjectNode checkCast(JsonNode document) {
...
+      throw new IllegalArgumentException("passage cannot be blank");
+    }
+
+    this.passage = Optional.ofNullable(passage);
     this.document = Objects.requireNonNull(document, "document cannot be null");
     this.scores = Objects.requireNonNull(scores, "scores cannot be null");
   }
 
+  /**
+   * Factory to create ane instance based on a document.
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java:69]: typo: ane -> an

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java [hunk 5]
```diff
@@ -38,16 +56,101 @@ private static ObjectNode checkCast(JsonNode document) {
...
+      int rank, Rank.RankSource rankSource, JsonNode document, PathMatchLocator passageLocator) {
+
+    Objects.requireNonNull(document, "document cannot be null");
+    Objects.requireNonNull(passageLocator, "passageLocator cannot be null");
+
+    var documentId =
+        switch (document.get(DOC_ID)) {
+          case null -> throw new IllegalArgumentException("Document id cannot be missing");
+          case NullNode ignored ->
+              throw new IllegalArgumentException("Document id cannot be a NullNode");
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java:87]: .... it is funny that we decided `null` as one of legal id types earlier :-D
(would be interesting to know if anyone ever uses it)

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java [hunk 6]
```diff
@@ -38,16 +56,101 @@ private static ObjectNode checkCast(JsonNode document) {
...
+        };
+
+    DocumentScores vectorScores;
+    var similarityField = document.get(VECTOR_FUNCTION_SIMILARITY_FIELD);
+    if (rankSource == Rank.RankSource.VECTOR) {
+      if (similarityField instanceof NumericNode numberNode) {
+        vectorScores = DocumentScores.fromVectorRead(numberNode.floatValue(), rank);
+      } else {
+        throw new IllegalArgumentException(
+            "%s document field is not a number or is missing for doc _id %s"
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java:98]: there's JsonUtil method `nodeTypeAsString(node)` for "pretty" type description fwtw ("Object", "Array", "Number", "<null>")

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/FindAndRerankOperationBuilder.java [hunk 7]
```diff
@@ -193,12 +201,6 @@ private void checkSupported() {
                 providerConfig.authentication(),
                 commandContext.commandName());
 
-    // we need a deferred action for each read
-    // at the moment we dont
-    List<DeferredCommandResult> deferredCommandResults =
-        List.of(new DeferredCommandResult(), new DeferredCommandResult());
-    List<Deferrable> deferrables = new ArrayList<>(deferredCommandResults);
-
     // todo: move to a builder pattern, mosty to make it eaier to manage the task position and retry
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/resolver/FindAndRerankOperationBuilder.java:204]: typo: eaier -> easier

**Review by tatu-at-datastax — APPROVED** [review]
LGTM, only some trivial nitpickings

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java (hunk 1 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java:164]: changed

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java (hunk 2 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/RerankingTask.java:175]: changed to 

```java
      var commandResult = deferredAndSource.deferredRead().commandResult();
      if (commandResult == null){
        throw new IllegalStateException("Deferred read from source %s returned null commandResult"
                  .formatted(deferredAndSource.rankSource()));
      }
```

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java (hunk 6 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/reranking/ScoredDocument.java:98]: changed 

```java
        throw new IllegalArgumentException(
            "%s document field is not a number or is missing type=%s _id=%s"
                .formatted(VECTOR_FUNCTION_SIMILARITY_FIELD, nodeTypeAsString(similarityField), documentId.asText()));
      }
```
