### PR TITLE
Fix #1811: fail cleanly on empty `name`

### LINKED ISSUE #1811: dropIndex with name = '' (empty string) throws StringIndexOutOfBoundsException
Running the following command against data-api 1.0.20:

```
{"dropTable":{"name":""}}
```

Here's the response I get:

```
HTTP error (500): {"status":{"ok":0},"errors":[{"message":"Server failed: root cause: (java.lang.StringIndexOutOfBoundsException) Index 0 out of bounds for length 0","errorCode":"SERVER_UNHANDLED_ERROR","id":"e9d9ba0b-3ac8-49d6-8f14-4bc1d31d72e4","family":"SERVER","title":"Server failed","scope":"DATABASE"}]}
```

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes error handling of `DropTable` with `name=""`.

**Which issue(s) this PR fixes**:
Fixes #1811

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/DropTableIntegrationTest.java [hunk 1]
```diff
@@ -78,9 +79,14 @@ public void dropTableWithIfExists() {
...
     }
+  }
 
+  @Nested
+  @Order(2)
+  @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
+  class DropTableFails {
     @Test
-    @Order(3)
+    @Order(1)
```
Comment (Hazel-Datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/DropTableIntegrationTest.java:89]: For `DropTableFails` tests, I think we don't need the order for each test?

**Review by Hazel-Datastax — APPROVED** [review]

File: src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/DropTableIntegrationTest.java (hunk 1 above)
Comment (tatu-at-datastax) [reply src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/DropTableIntegrationTest.java:89]: Probably not, I can remove those.

Comment (tatu-at-datastax) [reply src/test/java/io/stargate/sgv2/jsonapi/api/v1/tables/DropTableIntegrationTest.java]: Removed.

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:
