### PR TITLE
Fix #2266: remove dynamic Quarkus Config access by JsonApiException

### LINKED ISSUE #2266: Remove dynamic config access from `ApiException`
Requiring Quarkus Config object access from `ApiException.getCommandResultError()` is problematic (due to lack of injection). But 2 settings used can be determined without this access:

1. "debugEnabled" can be accessed using static `DebugConfigAccess`
2. "extendError" is always true, no longer disabled anywhere

This dynamic config access is causing class-loader issues for some exception handling so let's just remove it.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Removes one failure more wrt `ApiException` accessing Quarkus Config dynamically (outside of Dependency Injection), replacing with static accessor designed for purpose.

**Which issue(s) this PR fixes**:
Fixes #2266

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandConfig.java [hunk 1]
```diff
@@ -34,7 +34,7 @@ public class CommandConfig {
   private final ConcurrentMap<Class<?>, Object> configCache = new ConcurrentHashMap<>();
 
   // use getConfigProvider()
-  private SmallRyeConfig _config_provider = null;
+  private SmallRyeConfig _configProvider = null;
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandConfig.java]: Against naming convention, fixed.

File: src/main/java/io/stargate/sgv2/jsonapi/config/constants/OfflineModeSupport.java [hunk 2]
```diff
@@ -0,0 +1,14 @@
+package io.stargate.sgv2.jsonapi.config.constants;
+
+/**
+ * This class is used for determining "offline-mode" use of Data API (as a library) it does not use
+ * the Quarkus smallrye config system for detection, but is used by {@code CommandConfig} to
+ * determine need for alternate loading of Quarkus Smallrye configs.
+ */
+public class OfflineModeSupport {
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/config/constants/OfflineModeSupport.java]: Former "ApiConstants", better name.
