### PR TITLE
Fix 500s happen in Table Filter, Update columnAssignments, when codec not found, ToCQLCodecException

### LINKED ISSUE #1749: table update, wrong dataType for set operation, get 500 error
Table

`REATE TABLE filter.animal (
    id text,
    name text,
    age int,
    height smallint,
    description text,
    PRIMARY KEY ((id, name), age, height)`
    
Update

```json
{
    "updateOne": {
        "filter": {
            "id": "1",
            "name": "dqy",
            "age": 1,
            "height": 2
        },
        "update": {
            "$set": {
                "description": 123
            }
        }
    }
}
```

response

```json
{
    "errors": [
        {
            "message": "Server failed: root cause: (java.lang.RuntimeException) io.stargate.sgv2.jsonapi.exception.checked.ToCQLCodecException: Error trying to convert to targetCQLType `TEXT` from value.class `java.lang.Long`, value 123. Root cause: no codec matching value type",
            "errorCode": "SERVER_UNHANDLED_ERROR",
            "id": "ff27c5d5-8814-450a-bdf7-1ca5279e9d07",
            "family": "SERVER",
            "title": "Server failed",
            "scope": "DATABASE"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by Yuqi-Du**
This PR is to fix, the 500s server_unhandled error, which happen in Table Filter and Update Operation Path. 
We should map these 500s into corresponding API exception.

**Which issue(s) this PR fixes**:
Fixes #1749 #1740 #1744

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/query/ColumnAssignment.java [hunk 1]
```diff
@@ -82,13 +92,30 @@ protected void addPositionalValues(List<Object> positionalValues) {
               .codecToCQL(tableMetadata, column, rawValue)
               .toCQL(rawValue));
     } catch (MissingJSONCodecException e) {
-      // TODO: Better error handling
-      throw new RuntimeException(e);
+      throw DocumentException.Code.UNSUPPORTED_COLUMN_TYPES.get(
+          errVars(
+              TableSchemaObject.from(tableMetadata, new ObjectMapper()),
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/query/ColumnAssignment.java:97]: Pass `OBJECT_MAPPER` instead

File: src/main/resources/errors.yaml [hunk 2]
```diff
@@ -249,6 +240,17 @@ request-errors:
       
       ${SNIPPET.RESEND_USING_ONLY_DEFINED_COLUMNS}
 
+  - scope: FILTER
+    code: INVALID_FILTER_COLUMN_VALUES
+    title: Column value in filter is not valid
+    body: |-
+      Only values that are supported by the column data type can be included when filtering.
```
Comment (tatu-at-datastax) [inline src/main/resources/errors.yaml:247]: Not 100% sure but this might be misleading. Not sure which of the problems occurs here:

1. Filter refers to columns of types we do not support (like Counter). If so, message is bit misleading
2. Filter refers to supported column but JSON type not supported. If so, message makes sense.

So just wanted to check which case we have here.

Comment (tatu-at-datastax) [reply src/main/resources/errors.yaml:247]: Ok looking at test case(s), I think this is (2) so we are good. Sorry for the noise.

**Review by tatu-at-datastax — APPROVED** [review]
LGTM: suggested one improvement (wrt `ObjectMapper` use), but approved.

**Review by tatu-at-datastax — APPROVED** [review]
