### PR TITLE
Fix #1763: use right profile for Table truncate

### LINKED ISSUE #1763: Truncate (deleteMany without filter) uses wrong timeout for Tables
I noticed that attempts to truncate a Table (via Java client) fail with timeout of 10 seconds, against Test DBs. This is wrong since as per `src/main/resources/application.conf`:

```
  profiles {
    ...
    truncate {
      basic.request.timeout = 15 seconds
    }
    ...
    table-write {
      basic.request.timeout = 10 seconds
      consistency = LOCAL_QUORUM
    }
    table-truncate {
      basic.request.timeout = 15 seconds
      consistency = LOCAL_QUORUM
    }
```

timeout used should be 15 seconds. It seems likely wrong profile is being used for "delete all".
Exception passed by Data API is:

```
{ "message": "An unexpected server error occurred while processing the request. \n\nError Class: DriverTimeoutException\nError Message: Query timed out after 
 PT10S",
 "scope":"",
 "errorCode":"UNEXPECTED_SERVER_ERROR",
 "id":"4c17da72-d161-4bfd-bcdd-7d6e87e83846",
  "family":"SERVER",
 "title":"Unexpected server error"
}
```

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes minor copy-paste bug that caused #1763 (wrong timeout for Table truncate)

**Which issue(s) this PR fixes**:
Fixes #1763

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/CommandQueryExecutor.java [hunk 1]
```diff
@@ -58,8 +56,6 @@ private enum QueryType {
     }
   }
 
-  private static final Logger LOGGER = LoggerFactory.getLogger(CommandQueryExecutor.class);
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/CommandQueryExecutor.java:61]: Was not used, removed as basic clean up.

**Review by Hazel-Datastax — APPROVED** [review]
LGTM
