### PR TITLE
  Retry operation when fail due to missing ALLOW FILTERING

### LINKED ISSUE #1491: Add retry on ALLOW FILTERing required for ReadAttempt
following from #1448 

we will also need to handle the case where ALLOW FILTERING was not added, but should have been, because we will want to avoid adding it when not needed - as we must also give a warning about WHY we turned it on. 

if we get an error that allow filtering was needed, then we should retry the request. This will / must count towards one of the retries in the retry policy

### PR DESCRIPTION
**Pull request by amorton**
Fixes #1491 

Using a retry policy in the ReadAttempt to retry when allow
 filtering was not added, adds a warning to the attempt, and updates the CQL options for the query to retry.

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/test/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttemptTest.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+            .formatted(
+                TEST_DATA.names.KEYSPACE_NAME.asCql(true), TEST_DATA.names.TABLE_NAME.asCql(true));
+
+    fixture
+        .attempt()
+        .setStatus(OperationAttempt.OperationStatus.READY)
+        .queryExecutor()
+        .doExecuteReadThrowThenReturn(allowFilteringError, fixture.resultSet())
+        .attempt()
+        .assertCompleted()
```
Comment (Yuqi-Du) [inline src/test/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttemptTest.java:44]: Nit, wonder if the name should indicate it actually call execute for the attempt.
Similar to doExecuteReadThrowThenReturn() above, that one is more clear.

File: src/test/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttemptTest.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+        .attempt()
+        .verifyOnSuccessCalled(1, msg)
+        .attempt()
+        .verifyOnSuccessResultSet(fixture.resultSet(), msg)
+        .attempt()
+        .verifyOneWarning(WarningException.Code.QUERY_RETRIED_DUE_TO_INDEXING, msg)
+        .attempt()
+        .verifyWarningContains("The original query used the CQL: " + cql1, msg)
+        .attempt()
+        .verifyWarningContains("The original query used the parameters: " + List.of(), msg);
```
Comment (Yuqi-Du) [inline src/test/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttemptTest.java:66]: Cool, so verifyWarningContains called twice is for the convenience of checking msgs.

File: src/test/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptAssertions.java [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+  public FixtureT verifyOnSuccessCalled(int times, String message) {
+    verify(
+            target,
+            times(times)
+                .description("onSuccess() called %s times when: %s".formatted(times, message)))
+        .onSuccess(any());
+    return fixture;
+  }
+
+  public FixtureT verifyOnSuccessResultSet(AsyncResultSet expected, String message) {
```
Comment (Yuqi-Du) [inline src/test/java/io/stargate/sgv2/jsonapi/service/operation/OperationAttemptAssertions.java:166]: I saw you also check these times(x) method in multiple place.

Take OnSuccess as example.
When you do the fluent way of test in ReadAttemptTest.

You have this:

```
 .verifyOnSuccessCalled(1, msg)
 .attempt()
 .verifyOnSuccessResultSet(fixture.resultSet(), msg)
 .attempt()
```

verifyOnSuccessResultSet() is doing the amount of method call check again.
Wonder if these two can be combined?

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttempt.java [hunk 4]
```diff
@@ -166,4 +180,60 @@ static class ReadResult {
...
+      // clear the retry context so that we don't keep a reference to the last statement
+      var currentRetryContext = retryContext;
+      retryContext = null;
+
+      var allowFilteringMissing =
+          throwable instanceof InvalidQueryException
+              && throwable.getMessage().endsWith("use ALLOW FILTERING");
+
+      if (allowFilteringMissing) {
+        if (LOGGER.isWarnEnabled()) {
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttempt.java:211]: I think we definitely want this log line, correct?
I could image we may need to dig in some patterns or get some 'complains' from ALLOW FILTERING.

So, do we want to just log it anyway.
I don't know we set LOGGER.isWarnEnabled() anywhere.

**Review by Yuqi-Du — APPROVED** [review]
questions and some nit.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttempt.java (hunk 4 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttempt.java:211]: the next highest level to log is ERROR and dont think it is an error, happy to keep as an warn for now. Added a ticket for metrics for retry and retry when allow filtering https://github.com/stargate/data-api/issues/1583

File: src/test/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttemptTest.java (hunk 1 above)
Comment (amorton) [reply src/test/java/io/stargate/sgv2/jsonapi/service/operation/ReadAttemptTest.java:44]: discussing - assertExecuteCompleted() 

maybe also change the doExcecute etc to be when* - they were called do because it was originally using do() from mock library
