### PR TITLE
Fix #1787: add "bad" JSON along with "bad doc id" to help troubleshoting

### LINKED ISSUE #1787: Include JSON value that fails for `SHRED_BAD_DOCID_TYPE` (prod support)
I noticed a 1000 API failures for `InsertOne` with ErrorCode of `SHRED_BAD_DOCID_TYPE`.
Splunk logs look like:

```
{"commandName":"InsertOneCommand","tenant":"XXX","namespaceName":"NS","collectionName":"COLLECTION","schemaType":"COLLECTION","documentsReceived":"1","documentsReturned":"NA","errorList":[{"message":"Bad type for '_id' property: Document Id must be a JSON String, Number, Boolean, EJSON-Encoded Date Object or NULL instead got OBJECT","errorCode":"SHRED_BAD_DOCID_TYPE","id":"b0e300cc-2ace-44ce-9d20-a772c759a2ef","title":"Bad type for '_id' property","family":"REQUEST","scope":"DOCUMENT"}]}
   ]
```

so we know it's a JSON Object but not of EJSON-style. However, we don't know more details.

Log comes from exception message, so I think we should add actual JSON value serialization in addition to type, to help troubleshooting.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Includes actual JSON value that is not valid Doc `_id` for Collections (not just type like `OBJECT`). This to address a problem seen by on-call for a user who had 1000+ `SHRED_BAD_DOCID_TYPE` failures, to know what exactly went wrong.

NOTE: only one instance of error value needed changing, other 4 cases already have enough information.

**Which issue(s) this PR fixes**:
Fixes #1787

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Note: PR has unrelated minor warnings cleanup (unused local variables; misspellings) indicated by Idea.

File: src/main/java/io/stargate/sgv2/jsonapi/service/shredding/collections/DocumentId.java [hunk 1]
```diff
@@ -82,8 +82,8 @@ static DocumentId fromJson(JsonNode node) {
             "unrecognized JSON extension type '%s'", node.fieldNames().next());
     }
     throw ErrorCodeV1.SHRED_BAD_DOCID_TYPE.toApiException(
-        "Document Id must be a JSON String, Number, Boolean, EJSON-Encoded Date Object or NULL instead got %s",
-        node.getNodeType());
+        "Document Id must be a JSON String, Number, Boolean, EJSON-Encoded Date Object or NULL instead got %s: %s",
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/shredding/collections/DocumentId.java:85]: Actual change to include JSON value so logs show what actually was the mismatch (not just "there was a JSON Object")

File: src/test/java/io/stargate/sgv2/jsonapi/service/shredding/DocumentShredderTest.java [hunk 2]
```diff
@@ -331,10 +331,23 @@ public void docBadDocIdTypeArray() {
           catchThrowable(() -> documentShredder.shred(objectMapper.readTree("{ \"_id\" : [ ] }")));
 
       assertThat(t)
-          .isNotNull()
```
Comment (tatu-at-datastax) [inline src/test/java/io/stargate/sgv2/jsonapi/service/shredding/DocumentShredderTest.java:334]: No point in checking explicitly (noise); `null` covered by following checks.

**Review by amorton — APPROVED** [review]
