### PR TITLE
Table Sort, partitionKey not restricted in filter clause should trigger in-memory sort

### LINKED ISSUE #1718: HTTP 500 when sorting without constraining partition key
Using primary key `{ partitionBy: [ 'text' ], partitionSort: { int: 1 } }`:

```
An unexpected server error occurred while processing the request. 

Error Class: InvalidQueryException

Error Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.
```

```
CommandFailedEvent {
  command: {
    find: {
      filter: {},
      projection: undefined,
      sort: { int: 1 },
      options: {
        includeSimilarity: undefined,
        includeSortVector: undefined,
        limit: undefined,
        skip: undefined,
        pageState: undefined
      }
    }
  },
  keyspace: 'other_keyspace',
  source: 'test_table',
  commandName: 'find',
  url: 'https://178588f6-149c-4de5-b93c-3178d6d18e53-us-west-2.apps.astra-dev.datastax.com/api/json/v1/other_keyspace/test_table',
  duration: 398.36283399999957,
  error: DataAPIHttpError: HTTP error (500): {"data":{"documents":[],"nextPageState":null},"status":{"warnings":[{"errorCode":"ZERO_FILTER_OPERATIONS","message":"Zero filters were provided in the filter for this query. \n\nProviding zero filters will return all rows in the table, which may have poor performance when the table is large. For the best performance, include one or more filters using the primary key or indexes.\n\nThe table other_keyspace.test_table has the primary key: text(text), int(int).\nAnd has indexes on the columns: vector.\n\nThe query was executed without taking advantage of the primary key or indexes on the table, this can have performance implications on large tables.\n\nSee documentation at XXXX for best practices for filtering.","family":"REQUEST","scope":"WARNING","title":"Zero operations provided in query filter","id":"4d601c08-3bba-4179-9ef6-70ca2e6413c7"}]},"errors":[{"message":"An unexpected server error occurred while processing the request. \n\nError Class: InvalidQueryException\nError Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.","scope":"","errorCode":"UNEXPECTED_SERVER_ERROR","id":"8210575e-7c8b-4548-b2aa-e904b7c800cb","family":"SERVER","title":"Unexpected server error"}]}
      at DataAPIHttpClient._requestDataAPI (/Users/kavin.gupta/Documents/work/astra-db-ts/src/lib/api/clients/data-api-http-client.ts:212:15)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at DataAPIHttpClient.executeCommand (/Users/kavin.gupta/Documents/work/astra-db-ts/src/lib/api/clients/data-api-http-client.ts:169:12)
      at TableFindCursor._FindCursor_getMore (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:621:17)
      at TableFindCursor._FindCursor_next (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:586:9)
      at TableFindCursor.[Symbol.asyncIterator] (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:496:21)
      at TableFindCursor.toArray (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:554:22)
      at Object.testFn (/Users/kavin.gupta/Documents/work/astra-db-ts/tests/integration/documents/tables/cursor.test.ts:210:19)
      at tryCatchErr (/Users/kavin.gupta/Documents/work/astra-db-ts/tests/testlib/utils.ts:26:5)
      at /Users/kavin.gupta/Documents/work/astra-db-ts/tests/testlib/test-fns/parallel.ts:107:20
      at async Promise.all (index 0)
      at async Promise.all (index 0)
      at Context.<anonymous> (/Users/kavin.gupta/Documents/work/astra-db-ts/tests/testlib/test-fns/parallel.ts:113:17) {
    status: 500,
    body: '...',
    raw: {
      headers: {
        server: 'openresty/1.25.3.1',
        date: 'Thu, 14 Nov 2024 07:25:02 GMT',
        'content-type': 'application/json;charset=UTF-8',
        'content-length': '1228'
      },
      body: '{"data":{"documents":[],"nextPageState":null},"status":{"warnings":[{"errorCode":"ZERO_FILTER_OPERATIONS","message":"Zero filters were provided in the filter for this query. \\n\\nProviding zero filters will return all rows in the table, which may have poor performance when the table is large. For the best performance, include one or more filters using the primary key or indexes.\\n\\nThe table other_keyspace.test_table has the primary key: text(text), int(int).\\nAnd has indexes on the columns: vector.\\n\\nThe query was executed without taking advantage of the primary key or indexes on the table, this can have performance implications on large tables.\\n\\nSee documentation at XXXX for best practices for filtering.","family":"REQUEST","scope":"WARNING","title":"Zero operations provided in query filter","id":"4d601c08-3bba-4179-9ef6-70ca2e6413c7"}]},"errors":[{"message":"An unexpected server error occurred while processing the request. \\n\\nError Class: InvalidQueryException\\nError Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.","scope":"","errorCode":"UNEXPECTED_SERVER_ERROR","id":"8210575e-7c8b-4548-b2aa-e904b7c800cb","family":"SERVER","title":"Unexpected server error"}]}',
      status: 500,
      url: 'https://178588f6-149c-4de5-b93c-3178d6d18e53-us-west-2.apps.astra-dev.datastax.com/api/json/v1/other_keyspace/test_table',
      httpVersion: 2,
      statusText: ''
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Yuqi-Du**
Table 
```
CREATE TABLE filter.animal (
    id text,
    name text,
    age int,
    height smallint,
    description text,
    PRIMARY KEY ((id, name), age, height)
)
```
Given clustering keys are valid and not skipping.
Then, there are two rules for partitionKeys:

1. 
```
 SELECT *  FROM default_keyspace.animal  WHERE id = 'A1' AND name > 'Elephant' ORDER BY age ASC,height ASC  allow filtering;
InvalidRequest: Error from server: code=2200 [Invalid query] message="ORDER BY is only supported when the partition key is restricted by an EQ or an IN."
```
2. 
  ```
 SELECT *  FROM default_keyspace.animal  WHERE id = 'A1' and  name in ('Elephant','123') ORDER BY age ASC,height ASC ;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot page queries with both ORDER BY and a IN restriction on the partition key; you must either remove the ORDER BY or the IN and sort client side, or disable paging for this query"
```

So, in the Data API side,
```json
{
    "find": {
        "filter": {
            xxxxxx
        },
        "sort": {
            "age": 1,
            "height": 1
        }
    }
}
```
when there is no filter clause, in-memory sort should be trigger with warning.
Also, if not all partiontionKeys are restricted by $eq in the filter clause,  in-memory sort should be trigger with warning.

**Which issue(s) this PR fixes**:
Fixes #1718

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/sort/TableCqlSortClauseResolver.java [hunk 1]
```diff
@@ -142,6 +149,48 @@ private WithWarnings<OrderByCqlClause> resolveNonVectorSort(
...
+    // We know all the order keys are partition sorting keys and no clustering key missing or
+    // skipping.
+    // If not all partitionKeys are restricted by $eq, enable in memory sort
+    // CQL has below rules:
+    // 1. "ORDER BY is only supported when the partition key is
+    // restricted by an EQ or an IN."
+    // 2. "Cannot page queries with both ORDER BY and a IN restriction on the partition key; you
+    // must either remove the ORDER BY or the IN and sort client side, or disable paging for this
+    // query"
+    Set<CqlIdentifier> validPartitionKey = new HashSet<>();
```
Comment (amorton) [inline src/main/java/io/stargate/sgv2/jsonapi/service/resolver/sort/TableCqlSortClauseResolver.java:161]: as discussed, look at adding a proporty to the WhereCQLClause that returns true if the where clause has the necessary restirctions, and move this logic into the building of the TableWhereCqlClause

**Review by amorton — CHANGES_REQUESTED** [review]
see comment

**Review by amorton — APPROVED** [review]
udpated after discussions with yuqi
