### PR TITLE
Fixes #1692 - improved error for unsupported commands

### LINKED ISSUE #1692: Improve the error for commands that are not supported on tables, and table commands not on collections
Send this to a table 

```json
{
  "updateMany": {
      "filter" : {},
      "update": {}
}}
```
Get this back

```json
{
    "errors": [
        {
            "message": "Server internal error: UpdateManyCommand Command does not support operating on Tables, target was SchemaObjectName[keyspace=demo, table=collections]",
            "errorCode": "SERVER_INTERNAL_ERROR",
            "id": "ee5c2ae9-3731-4379-926b-e979e22de6b5",
            "title": "Server internal error",
            "family": "SERVER",
            "scope": "EMPTY"
        }
    ]
}
```

This is handled in the `CommandResolver` interface with defaults so easy to change all in one place 

bonus points if the error is specific for tables or collections and can list all the commands that are supported for each by iterating an enum or such

### PR DESCRIPTION
**Pull request by amorton**
Moved the CommandName and related enums to be top level as they are used in multiple places and not a sub component of the Commmand interface.

Fixes #1692

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+  CREATE_COLLECTION("createCollection", CommandType.DDL, CommandTarget.KEYSPACE),
+  CREATE_INDEX("createIndex", CommandType.DDL, CommandTarget.TABLE),
+  CREATE_VECTOR_INDEX("createVectorIndex", CommandType.DDL, CommandTarget.TABLE),
+  CREATE_KEYSPACE("createKeyspace", CommandType.DDL, CommandTarget.DATABASE),
+  CREATE_NAMESPACE("createNamespace", CommandType.DDL, CommandTarget.DATABASE),
+  CREATE_TABLE("createTable", CommandType.DDL, CommandTarget.KEYSPACE),
+  DELETE_COLLECTION("deleteCollection", CommandType.DDL, CommandTarget.KEYSPACE),
+  DELETE_MANY("deleteMany", CommandType.DML, CommandTarget.TABLE, CommandTarget.COLLECTION),
+  DELETE_ONE("deleteOne", CommandType.DML, CommandTarget.TABLE, CommandTarget.COLLECTION),
+  DROP_INDEX("dropIndex", CommandType.DML, CommandTarget.KEYSPACE),
```
Comment (maheshrajamani) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java:29]: Drop index is not a DML command

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  DROP_NAMESPACE("dropNamespace", CommandType.DDL, CommandTarget.DATABASE),
+  DROP_KEYSPACE("dropKeyspace", CommandType.DDL, CommandTarget.DATABASE),
+  DROP_TABLE("dropTable", CommandType.DDL, CommandTarget.KEYSPACE),
+  ESTIMATED_DOCUMENT_COUNT("estimatedDocumentCount", CommandType.DML, CommandTarget.COLLECTION),
+  FIND_COLLECTIONS("findCollections", CommandType.DDL, CommandTarget.KEYSPACE),
+  FIND("find", CommandType.DML, CommandTarget.TABLE, CommandTarget.COLLECTION),
+  FIND_EMBEDDING_PROVIDERS("findEmbeddingProviders", CommandType.DML, CommandTarget.DATABASE),
```
Comment (maheshrajamani) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java:36]: This should be a CommandTarget.SYSTEM. As per comment on top of this class, this along with offline commands needs to to have a new CommandType.ADMIN

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+  FIND_NAMESPACES("findNamespaces", CommandType.DDL, CommandTarget.DATABASE),
+  FIND_KEYSPACES("findKeyspaces", CommandType.DDL, CommandTarget.DATABASE),
+  FIND_ONE_AND_DELETE("findOneAndDelete", CommandType.DML, CommandTarget.COLLECTION),
+  FIND_ONE_AND_REPLACE("findOneAndReplace", CommandType.DML, CommandTarget.COLLECTION),
+  FIND_ONE_AND_UPDATE("findOneAndUpdate", CommandType.DML, CommandTarget.COLLECTION),
+  FIND_ONE("findOne", CommandType.DML, CommandTarget.TABLE, CommandTarget.COLLECTION),
+  INSERT_MANY("insertMany", CommandType.DML, CommandTarget.TABLE, CommandTarget.COLLECTION),
+  INSERT_ONE("insertOne", CommandType.DML, CommandTarget.TABLE, CommandTarget.COLLECTION),
+  LIST_INDEXES("listIndexes", CommandType.DDL, CommandTarget.TABLE),
+  LIST_TABLES("listTables", CommandType.DDL, CommandTarget.KEYSPACE),
```
Comment (maheshrajamani) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java:46]: This should be CommandTarget.TABLE, the command doesn't return collections.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+import java.util.List;
+import java.util.Set;
+import java.util.stream.Collectors;
+import java.util.stream.Stream;
+
+/**
+ * The canonical list of commands the API support, any command name not listed here is not a
+ * command.
+ */
+public enum CommandName {
```
Comment (maheshrajamani) [inline src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java:12]: The enum name doesn't make sense, since it has more information than it's name, need to be renamed something like CommandInfo.

**Review by maheshrajamani — COMMENTED** [review]
Changes looks good, added few recommendations.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java (hunk 1 above)
Comment (maheshrajamani) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java]: Fixed it.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java (hunk 2 above)
Comment (maheshrajamani) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java]: Added a CommandType.ADMIN and used it for this command.

File: src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java (hunk 4 above)
Comment (maheshrajamani) [reply src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandName.java:12]: this can be taken as separate PR as the name was an existing one. Created this [issue](https://github.com/stargate/data-api/issues/1701) for tracking.

**Review by maheshrajamani — APPROVED** [review]
LGTM

**Comment by tatu-at-datastax** [comment]
Ok would have been good to discuss this wrt #1592 / PR #1645 first.
