### PR TITLE
Fix `Unable to parse embedding provider response message` errors from Bedrock `amazon.titan-embed-text-v2:0`

### LINKED ISSUE #1486: Unexpected Field "embeddingsByType" in Response from `amazon.titan-embed-text-v2:0` Model Causing Deserialization Error
Bedrock model `amazon.titan-embed-text-v2:0` returns `Unable to parse embedding provider response message` error message. 

The actual exception is from the deserialization due to the appearance of an unexpected `embeddingsByType` field in the response. This field was not present in previous responses, and its recent addition is causing the following error:
```
Unrecognized field "embeddingsByType" (class io.stargate.sgv2.jsonapi.service.embedding.operation.AwsBedrockEmbeddingProvider$EmbeddingResponse), not marked as ignorable
```

### PR DESCRIPTION
**Pull request by Hazel-Datastax**
**What this PR does**:
Fix `Unable to parse embedding provider response message` errors from Bedrock `amazon.titan-embed-text-v2:0`

The actual exception is from the deserialization due to the appearance of an unexpected `embeddingsByType` field in the response. Add ` @JsonIgnoreProperties({ "embeddingsByType" })` to fix it

**Which issue(s) this PR fixes**:
Fixes #1486 

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/embedding/operation/AwsBedrockEmbeddingProvider.java [hunk 1]
```diff
@@ -161,6 +162,7 @@ public Uni<Response> vectorize(
   private record EmbeddingRequest(
       String inputText, @JsonInclude(value = JsonInclude.Include.NON_DEFAULT) int dimensions) {}
 
+  @JsonIgnoreProperties(ignoreUnknown = true)
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/embedding/operation/AwsBedrockEmbeddingProvider.java:165]: Doing this will ignore all properties, which may be ok. Alternatively could use

   @JsonIgnoreProperties({ "embeddingsByType" })

to just ignore specific unknown property. I'll let you decide which makes more sense.

**Review by tatu-at-datastax — APPROVED** [review]
That should work -- would there be any way to test this? I guess our manually run embedding provider test suite would do that?

I added one note on alternative handling; feel free to use or ignore whatever makes most sense.

**Comment by Hazel-Datastax** [comment]
> That should work -- would there be any way to test this? I guess our manually run embedding provider test suite would do that?
> 
> I added one note on alternative handling; feel free to use or ignore whatever makes most sense.

Yes, the test suite covers that
