### PR TITLE
Fixes #2013: avoid fail for createCollection wrt legacy collections (pre-lexical/pre-rerank)

### LINKED ISSUE #2013: Reranking and Lexical feature enabled in production caused backwards compatibility issue for createCollection.
Data API rollout the hybrid search in certain Astra production kube, which will enable lexical and reranking features by default.
So 'legacy' collection created before the feature rollout won't have lexical and reranking setting. 
But now since Data API will include the lexical and reranking to the command by default, the createCollection command won't be idempotent in this situation, and will error out as EXISTING_COLLECTION_DIFFERENT_SETTINGS.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes issue wrt "createCollection" failing for legacy Collections created before lexical/rerank functionality, due to changing defaults.
Will prevent throwing exception if:

1. Existing collection that has no lexical or reranking config
2. New creation that relies on default settings for lexical and reranking config

This should no longer fail as it considers "defaults are defaults" (despite defaults effectively changing for new Collections) 

**Which issue(s) this PR fixes**:
Fixes #2013

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 1]
```diff
@@ -162,11 +163,38 @@ public Uni<Supplier<CommandResult>> execute(
...
+              == CollectionLexicalConfig.configForPreLexical()
+          && existingCollectionSettings.rerankingConfig()
+              == CollectionRerankDef.configForPreRerankingCollection()) {
+        newCollectionSettings =
+            newCollectionSettings.withLexicalAndRerankOverrides(
+                existingCollectionSettings.lexicalConfig(),
+                existingCollectionSettings.rerankingConfig());
+        // and now re-check if settings are the same
+        sameSettings = existingCollectionSettings.equals(newCollectionSettings);
+        logger.info(
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:187]: Adding this so we get some visibility into how often override needed, works.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 2]
```diff
@@ -402,9 +440,15 @@ TableMetadata findTableAndValidateLimits(
     return null;
   }
 
-  public SimpleStatement getCreateTable(String keyspace, String table) {
+  public static SimpleStatement getCreateTable(
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:443]: Changing this to `static` since we should be using that from some of Integration tests (unfortunately we have copy-pasted versions). Also ensures all arguments are explicitly passed since call paths differ a bit wrt overrides, specifically "lexicalConfig".

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 3]
```diff
@@ -428,27 +472,26 @@ public SimpleStatement getCreateTable(String keyspace, String table) {
         createTableWithVector = createTableWithVector + " WITH comment = '" + comment + "'";
       }
       return SimpleStatement.newInstance(String.format(createTableWithVector, keyspace, table));
-    } else {
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:431]: No functional change, just remove unnecessary "else" scope.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 4]
```diff
@@ -162,11 +163,38 @@ public Uni<Supplier<CommandResult>> execute(
             embeddingSourceModel,
             comment,
             objectMapper);
-    // if table exists we have two choices:
+    // if table exists we have a choice:
     // (1) trying to create with same options -> ok, proceed
     // (2) trying to create with different options -> error out
-    if (existedCollectionSettings.equals(newCollectionSettings)) {
-      return executeCollectionCreation(dataApiRequestInfo, queryExecutor, true);
+    // but note that for case (1) we need to consider backwards-compatibility
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:169]: this line may need some tweak?

case (1) is saying oldSetting and newSetting are the same, but our special handing happens when they are **not** the same and then override the newSetting, then re-compare.

maybe changed to (Feel free to not change or adapt)
```
but note that for case (2), we need to consider backwards-compatibility, as we have collections created before some of the settings were added(namely, lexical and reranking settings), and now added in newCollectionSettings.
```

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 5]
```diff
@@ -162,11 +163,38 @@ public Uni<Supplier<CommandResult>> execute(
...
+          && existingCollectionSettings.rerankingConfig()
+              == CollectionRerankDef.configForPreRerankingCollection()) {
+        newCollectionSettings =
+            newCollectionSettings.withLexicalAndRerankOverrides(
+                existingCollectionSettings.lexicalConfig(),
+                existingCollectionSettings.rerankingConfig());
+        // and now re-check if settings are the same
+        sameSettings = existingCollectionSettings.equals(newCollectionSettings);
+        logger.info(
+            "CreateCollectionOperation for {}.{} with legacy lexical/reranking settings: unification successful? {}",
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:188]: `unification successful?` do we need the question mark.

also, would it be redundant to also log the old and new collectionSetting

File: src/main/java/io/stargate/sgv2/jsonapi/service/schema/collections/CollectionLexicalConfig.java [hunk 6]
```diff
@@ -125,18 +131,26 @@ public static CollectionLexicalConfig validateAndConstruct(
...
   /**
-   * Accessor for an instance to use for "lexical disabled" cases: either for existing collections
-   * without lexical config, or envi
+   * Accessor for a singleton instance used to represent case of default lexical configuration for
+   * newly created Collections that do not specify lexical configuration.
    */
-  public static CollectionLexicalConfig configForDisabled() {
-    return new CollectionLexicalConfig(false, null);
+  public static CollectionLexicalConfig configForDefault() {
+    return DEFAULT_CONFIG;
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/schema/collections/CollectionLexicalConfig.java:146]: This is nice to uniform both DEFAULT_CONFIG and MISSING_CONFIG.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java (hunk 4 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:169]: Good point, comment does not explain what we do... will tweak.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java (hunk 5 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:188]: Good idea: `CollectionSchemaObject.toString()` has `toString()` so I can do that.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java (hunk 4 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java]: Changed, I hope it reads better now.

**Review by Yuqi-Du — APPROVED** [review]
approved

File: src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/VectorConfig.java [hunk 7]
```diff
@@ -167,6 +167,16 @@ public int hashCode() {
     return Objects.hash(columnVectorDefinitions, vectorEnabled);
   }
 
+  @Override
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/cqldriver/executor/VectorConfig.java:170]: Was missing, noticed from new log lines I added.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java [hunk 8]
```diff
@@ -162,11 +163,58 @@ public Uni<Supplier<CommandResult>> execute(
...
+
+      // So: for backwards compatibility reasons we may need to override settings if
+      // (and only if) the collection was created before lexical and reranking.
+      // In addition, we need to check that new lexical settings are for defaults
+      // (difficult to check the same for reranking; for now assume that if lexical
+      // is default, reranking is also default).
+      if (oldLexical == CollectionLexicalConfig.configForPreLexical()
+          && newLexical == CollectionLexicalConfig.configForDefault()
+          && existingCollectionSettings.rerankingConfig()
+              == CollectionRerankDef.configForPreRerankingCollection()) {
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:189]: Miss one item here for rerank?

Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java:189]: unfortunately no; we do not have "default" entry for reranking, so cannot use identity comparison. :-/
So that's a limitation -- comment above tries to explain it.

File: src/main/java/io/stargate/sgv2/jsonapi/service/reranking/configuration/RerankingProviderConfigProducer.java [hunk 9]
```diff
@@ -71,6 +72,11 @@ RerankingProvidersConfig produce(
     }
 
     validateRerankingProvidersConfig(rerankingProvidersConfig);
+
+    // Initialize the default reranking provider and model in DefaultRerankingProviderDef as
+    // Singleton.
+    CollectionRerankDef.initializeDefaultRerankDef(rerankingProvidersConfig);
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/reranking/configuration/RerankingProviderConfigProducer.java:78]: I wish we did not need to do this -- relying on state of Quarkus initialization. But I understand why it is necessary for what we need.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java (hunk 8 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/collections/CreateCollectionOperation.java]: update: Yuqi committed a fix to this omission so we are all good!
