### PR TITLE
Fix `findOne`/`find` wrt `_id` column (actually all filterables)

### LINKED ISSUE #1357: Not able to filter by _id with tables
(see #1349 for background)

After fixing #1349, it will be possible to use "non-standard" column names, ones that must be quoted in CQL. But there appears to be a special case for column `_id`, likely due to special handling given to it with Collections.
So while:

1. One can create Table with `_id` column AND
2. insert rows with `_id`

`findOne()` and `find() commands seem to fail with strange failure related to filtering:

```
    "errors": [
        {
            "message": "Server internal error: Filter type not supported, unable to resolve to a filtering strategy",
            "errorCode": "SERVER_INTERNAL_ERROR",
            "exceptionClass": "JsonApiException"
```

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes handling of `_id` column wrt Find operations: there is something specific about this compared to all other ids (quoted or not)

**Which issue(s) this PR fixes**:
Fixes #1357

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Ok, this turns out to be rather difficult to solve: basically `FilterClauseDeserializer` has quite specific handling for `_id` (DOC_ID), in:

https://github.com/stargate/data-api/blob/24af4e2cfe49689916113ba6d90719fc195c032d/src/main/java/io/stargate/sgv2/jsonapi/api/model/command/deserializers/FilterClauseDeserializer.java#L336 

which creates value type not matched by filter resolved for Tables.

Conceptually it'd be good for deserializer to skip this special handling for Tables, but piping through that information proves difficult given that deserialization is invoked by Quarkus, via type on endpoint.

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/matcher/TableFilterResolver.java [hunk 1]
```diff
@@ -75,20 +90,44 @@ private static List<DBFilterBase> findDynamic(CaptureExpression captureExpressio
...
       } else if (captureExpression.marker() == DYNAMIC_NUMBER_GROUP) {
         filters.add(
             new NumberTableFilter(
                 captureExpression.path(),
                 NativeTypeTableFilter.Operator.from(
                     (ValueComparisonOperator) filterOperation.operator()),
-                (BigDecimal) filterOperation.operand().value()));
+                (BigDecimal) rhsValue));
+      } else if (captureExpression.marker() == DYNAMIC_DOCID_GROUP) {
+        Object actualValue = ((DocumentId) rhsValue).value();
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/resolver/matcher/TableFilterResolver.java:109]: Should probably be refactored to avoid duplicating code to create Text/NumberTableFilter.

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/matcher/TableFilterResolver.java [hunk 2]
```diff
@@ -75,20 +90,44 @@ private static List<DBFilterBase> findDynamic(CaptureExpression captureExpressio
...
+                  NativeTypeTableFilter.Operator.from(
+                      (ValueComparisonOperator) filterOperation.operator()),
+                  (BigDecimal) actualValue));
+        } else {
+          throw new UnsupportedOperationException(
+              "Unsupported DocumentId type: " + rhsValue.getClass().getName());
+        }
+      } else {
+        throw new UnsupportedOperationException(
+            "Unsupported dynamic filter type: " + filterOperation);
```
Comment (Yuqi-Du) [inline src/main/java/io/stargate/sgv2/jsonapi/service/resolver/matcher/TableFilterResolver.java:130]: I know this is just following the pattern. We can change these to Data API exception later.

**Review by Yuqi-Du — APPROVED** [review]
LGTM!

**Comment by vkarpov15** [comment]
I confirmed yesterday that this works in https://github.com/stargate/stargate-mongoose-sample-apps/pull/397

File: src/main/java/io/stargate/sgv2/jsonapi/service/resolver/matcher/TableFilterResolver.java (hunk 2 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/resolver/matcher/TableFilterResolver.java:130]: Yes, sorry I missed this one before merging.

**Comment by tatu-at-datastax** [comment]
Thank you for verifying @vkarpov15 !
