### PR TITLE
Fix #1578: deleteOne of row with Blob in PK

### LINKED ISSUE #1578: Cannot deleteOne when a blob is part of the PK (Tables, v1.0.18)
When trying a deleteOne on a Table with this in the primary key:

```
...
                "p_blob": {
                    "type": "blob"
                },
...
```

the deleteOne looking like this:

```
{
    "deleteOne": {
        "filter": {
            "p_ascii": "abc",
            "p_bigint": 10000,
            "p_blob": {
                "$binary": "q83vASNFZ4k="
            },
            "p_boolean": false
       }
    }
}
```

the command fails with HTTP 200 and:

```
{
    "errors": [
        {
            "message": "Server internal error: Unrecognized JsonExtensionType: BINARY",
            "errorCode": "SERVER_INTERNAL_ERROR"
        }
    ]
}
```

Note: if trying the relaxed repr. in the `filter`, i.e. `... "p_blob": "q83vASNFZ4k=", ...`, the error becomes _Server failed: root cause: (io.stargate.sgv2.jsonapi.exception.catchable.ToCQLCodecException) Error trying to convert to targetCQLType `BLOB` from value.class `java.lang.String`, value \"q83vASNFZ4k=\". Root cause: no codec matching value type_ instead.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fixes problem with deleting rows that have a Blob in primary key

**Which issue(s) this PR fixes**:
Fixes #1578

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Ok: fix included -- should be extensible for other EJSON types.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/codecs/BinaryTableFilter.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package io.stargate.sgv2.jsonapi.service.operation.filters.table.codecs;
```
Comment (Hazel-Datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/codecs/BinaryTableFilter.java:1]: nit: I saw other `TableFilter`s are in `package io.stargate.sgv2.jsonapi.service.operation.filters.table`; maybe move it to there?

**Review by Hazel-Datastax — APPROVED** [review]
LGTM

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/codecs/BinaryTableFilter.java (hunk 1 above)
Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/codecs/BinaryTableFilter.java:1]: Good catch! Will move. Thank you!

Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/codecs/BinaryTableFilter.java]: Fixed, waiting for CI.
