### PR TITLE
Fixes #1200: add handling for invalid JSON requests

### LINKED ISSUE #1200: Invalid non-JSON request ("Unexpected character") results in `SERVER_UNHANDLED_ERROR` 500 failure
Going through unmapped exceptions in Splunk logs, I see exceptions like:

```
Unrecognized exception caught, mapped to SERVER_UNHANDLED_ERROR: Unexpected 
character ('d' (code 100)): was expecting double-quote to start field name
```

which suggests invalid payload (malformed "JSON") where client sends unquoted JSON Field names

```
{debug: true}
```

Or something.

Unfortunately logging currently does not include source content (will file separate issue for enabling)

Full stack trace:

```
stackTrace: : com.fasterxml.jackson.core.JsonParseException: Unexpected character ('d' (code 100)): was expecting double-quote to start field name
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 2, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2481)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:752)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:676)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:2147)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1797)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:801)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:95)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2125)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1501)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.doReadFrom(ServerJacksonMessageBodyReader.java:87)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:38)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:77)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
```

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds exception mapper for `JsonParseException` to handle low-level JSON parse failures.

**Which issue(s) this PR fixes**:
Fixes #1200

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by kathirsvn — APPROVED** [review]
LGTM

File: src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java [hunk 1]
```diff
@@ -180,6 +187,19 @@ private static CommandResult.Error handleAllNodesFailedException(
...
+      JacksonException e, String message) {
+    // Low-level parsing problem?
+    if (e instanceof JsonParseException) {
+      return ErrorCode.INVALID_REQUEST_NOT_JSON
+          .toApiException("underlying problem: (%s) %s", e.getClass().getName(), message)
+          .getCommandResultError(Response.Status.OK);
+    }
+
+    // Will need to add more handling but start with above
+    return handleUnrecognizedException(e, message);
```
Comment (kathirsvn) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java:200]: Agreed on the comment above. Since, we know this is one of `JacksonException`, we can keep adding more known jackson errors.

Comment (tatu-at-datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java:200]: Exactly. I plan to follow up on this asap.
