### PR TITLE
Fix #1349: support "non-standard" column names

### LINKED ISSUE #1349: Not able to use column names with upper-case letters, special characters
I created a keyspace in cqlsh:

```
CREATE KEYSPACE demo
  WITH REPLICATION = { 
   'class' : 'SimpleStrategy', 
   'replication_factor' : 1 
  };

```

Create table with `_id` as the primary key:

```
CREATE TABLE bots (
   "_id"           text, 
   name         text,
   PRIMARY KEY ("_id"));
```

Insert a new row into the table:

```
INSERT INTO bots ("_id", name) VALUES ('000000000000000000000000', 'test');
```

Send a curl command to filter by `_id` and you get a `Filter type not supported` error:

```
$ curl -H 'Content-Type: application/json' -H 'X-Cassandra-Token: Cassandra:Y2Fzc2FuZHJh:Y2Fzc2FuZHJh' -X POST -d '{"findOne":{"filter":{"_id":"000000000000000000000000"},"options":{}}}' http://127.0.0.1:8181/v1/demo/bots 
{"errors":[{"message":"Server internal error: Filter type not supported, unable to resolve to a filtering strategy","errorCode":"SERVER_INTERNAL_ERROR"}]}
$
```

This only seems to happen with _id, replace _id with id and this works fine.

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Fix issue(s) in filtering (and insertion) by column names that require quoting (have upper-case letters; non-alphanumerics, start with underscore etc etc)

**Which issue(s) this PR fixes**:
Fixes #1349

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/NativeTypeTableFilter.java [hunk 1]
```diff
@@ -108,11 +108,10 @@ public <StmtT extends OngoingWhereClause<StmtT>> StmtT apply(
     try {
       var codec =
           JSONCodecRegistry.codecToCQL(
-              tableSchemaObject.tableMetadata, CqlIdentifier.fromCql(path), columnValue);
+              tableSchemaObject.tableMetadata, getPathAsCqlIdentifier(), columnValue);
       positionalValues.add(codec.toCQL(columnValue));
     } catch (UnknownColumnException e) {
-      // TODO AARON - Handle error
-      throw new RuntimeException(e);
+      throw ErrorCode.TABLE_COLUMN_UNKNOWN.toApiException(e.getMessage());
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/NativeTypeTableFilter.java:114]: Changes 500 SERVER_INTERNAL into proper failure when referencing unknown column in filter, projection etc clauses.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/NativeTypeTableFilter.java [hunk 2]
```diff
@@ -122,6 +121,6 @@ public <StmtT extends OngoingWhereClause<StmtT>> StmtT apply(
     }
 
     return ongoingWhereClause.where(
-        Relation.column(path).build(operator.predicate.cql, bindMarker()));
+        Relation.column(getPathAsCqlIdentifier()).build(operator.predicate.cql, bindMarker()));
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/filters/table/NativeTypeTableFilter.java:124]: Another important fix: instead of passing column name as `String` needs to pass as `CqlIdentifier` to retain casing etc.

File: src/main/java/io/stargate/sgv2/jsonapi/service/operation/query/DBFilterBase.java [hunk 3]
```diff
@@ -30,6 +31,8 @@ public abstract class DBFilterBase implements Supplier<BuiltCondition> {
 
   public final IndexUsage indexUsage;
 
+  private transient CqlIdentifier pathAsIdentifier;
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/operation/query/DBFilterBase.java:34]: Lazily constructed when needed.

**Review by Yuqi-Du — APPROVED** [review]

**Review by vkarpov15 — COMMENTED** [review]
Code is LGTM, will test this out on Sunday or Monday

**Comment by vkarpov15** [comment]
Confirmed that I can now query by indexed camelCase property names, but still getting "Filter type not supported, unable to resolve to a filtering strategy" when filtering by _id.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 yes, I filed #1357 for that part, was unable to resolve on friday but hope to fix today.
