### PR TITLE
Map Java driver ReadFailureException on Find command to JsonApiException

### LINKED ISSUE #949: Java driver ReadFailureException on Find command
The following Java driver exception was observed in log files on a Find command:

```
[s698|1374531830][Node(endPoint=/127.0.0.1:9042, hostId=<redacted>, hashCode=4ebf5df3)] Error (6 ms) [2 values] SELECT key, tx_id, doc_json, SIMILARITY_COSINE(query_vector_value, ?) FROM default_keyspace.my_collection ORDER BY query_vector_value ANN OF ? LIMIT 4
Command 'FindCommand' failed with exception: com.datastax.oss.driver.api.core.servererrors.ReadFailureException: Cassandra failure during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded, 1 failed)
```

This probably needs to be retried, and if failure recurs, we need to map to a JsonApiException with appropriate error message.

### PR DESCRIPTION
**Pull request by Hazel-Datastax**
**What this PR does**:
Map Java driver ReadFailureException on Find command to JsonApiException

**Which issue(s) this PR fixes**:
Fixes #949 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java [hunk 1]
```diff
@@ -120,6 +121,11 @@ public final class ThrowableToErrorMapper {
               .getCommandResultError(message, Response.Status.INTERNAL_SERVER_ERROR);
           // Unidentified Driver Exceptions, will not map into JsonApiException
         } else if (throwable instanceof DriverException) {
+          if (throwable instanceof ReadFailureException) {
+            return ErrorCode.DATABASE_READ_FAILED
+                .toApiException()
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/exception/mappers/ThrowableToErrorMapper.java:126]: I think we should include actual underlying error message for extra information: something like:

    .toApiException("root cause: (%s) %s", throwable.getClass().getName(), throwable.getMessage())

**Review by tatu-at-datastax — COMMENTED** [review]
Change makes sense; but I think someone else should double-check whether testing makes sense as suggested.

**Review by tatu-at-datastax — APPROVED** [review]
