### PR TITLE
Use the ExceptionMappers pattern to handle socket timeouts from model providers 

### LINKED ISSUE #2367: NoStackTraceTimeoutException when embedding/reranking providers timed out
To reproduce, first change the timeout setting in `OpenAIEmbeddingProvider`:
```
    openAIClient =
        QuarkusRestClientBuilder.newBuilder()
            .baseUri(URI.create(serviceConfig.getBaseUrl(modelName())))
            .readTimeout(10, TimeUnit.MILLISECONDS) <--- change the timeout
            .build(OpenAIEmbeddingProviderClient.class);
```

then send a find/insert request:
```
{
    "insertOne": {
        "document": {
            "$vectorize" : "abc"
        }
    }
}
```

You will get the `UNEXPECTED_SERVER_ERROR` and `NoStackTraceTimeoutException` inside
```
{
    "errors": [
        {
            "id": "191a0ee1-6cf9-4091-a490-73d2a6fd47ff",
            "family": "SERVER",
            "scope": "",
            "errorCode": "UNEXPECTED_SERVER_ERROR",
            "title": "Unexpected server error",
            "message": "An unexpected server error occurred while processing the request. \n\nError Class: NoStackTraceTimeoutException\nError Message: The timeout of 10 ms has been exceeded when getting a connection to api.openai.com:443\n\nReview the Error Message before retrying this request."
        }
    ]
}
```

I fixed this problem before with PR https://github.com/stargate/data-api/pull/1139 by adding fixes in ThrowableToErrorMapper -> because quarkus throws TimeoutException in this case
```
        // TimeoutException from quarkus
        if (throwable instanceof TimeoutException) {
          return ErrorCode.EMBEDDING_PROVIDER_TIMEOUT
              .toApiException()
              .getCommandResultError(Response.Status.OK);
        }
```

Now the ThrowableToErrorMapper has been removed and the logic has been changed. The problem surfaces again. 

This issue it also related to https://github.com/stargate/data-api/issues/2134

### PR DESCRIPTION
**Pull request by amorton**
Use the ExceptionMappers pattern to handle socket timeouts from model providers 

**Which issue(s) this PR fixes**:
Fixes #2367

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/embedding/operation/EmbeddingProvider.java [hunk 1]
```diff
@@ -203,17 +206,6 @@ protected int atMostRetries() {
...
-  protected boolean decideRetry(Throwable throwable) {
-
-    var retry =
-        (throwable.getCause() instanceof APIException apiException
-            && apiException.code.equals(
-                EmbeddingProviderException.Code.EMBEDDING_PROVIDER_TIMEOUT.name()));
-
-    return retry || super.decideRetry(throwable);
-  }
-
```
Comment (Hazel-Datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/embedding/operation/EmbeddingProvider.java]: Why do we want to remove this?

File: src/main/java/io/stargate/sgv2/jsonapi/service/provider/RerankingProviderExceptionHandler.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+public class RerankingProviderExceptionHandler extends DefaultProviderExceptionHandler {
+
+  public RerankingProviderExceptionHandler(ModelProvider modelProvider, ModelType modelType) {
+    super(modelProvider, modelType);
+  }
+
+  @Override
+  public Throwable handle(TimeoutException exception) {
+
+    return EmbeddingProviderException.Code.EMBEDDING_PROVIDER_TIMEOUT.get(
```
Comment (Hazel-Datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/provider/RerankingProviderExceptionHandler.java]: Should be `RerankingProviderException.Code.RERANKING_PROVIDER_TIMEOUT`

**Review by Hazel-Datastax — APPROVED** [review]

File: src/main/java/io/stargate/sgv2/jsonapi/service/provider/RerankingProviderExceptionHandler.java (hunk 2 above)
Comment (amorton) [reply src/main/java/io/stargate/sgv2/jsonapi/service/provider/RerankingProviderExceptionHandler.java]: fixed
