### PR TITLE
Convert `EMBEDDING_` related codes and V1 codes used in EGW to V2

### LINKED ISSUE #2285: Convert `ErrorCodeV1` error codes (~40 remaining) to new ("V2") variant
Older code (mostly Collection-related) uses `ErrorCodeV1` and `JsonApiException` for reporting problems.
But we have newer facilities for doing this: `ErrorCode` and more granular exception/code hierarchy, including external templating (`errors.yaml`).

So let's start converting: 116 to go, with hundreds of usages.

### PR DESCRIPTION
**Pull request by Hazel-Datastax**
**What this PR does**:
Convert all the `EMBEDDING_` related codes and the V1 codes used in EGW to V2. 
Have another PR https://github.com/riptano/embedding-gateway/pull/154 in EGW to fit this change

**Which issue(s) this PR fixes**:
Fixes #2285

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/io/stargate/sgv2/jsonapi/service/reranking/operation/NvidiaRerankingProvider.java [hunk 1]
```diff
@@ -79,7 +79,7 @@ public NvidiaRerankingProvider(
     nvidiaClient =
         QuarkusRestClientBuilder.newBuilder()
             .baseUri(URI.create(modelConfig.url()))
-            .readTimeout(modelConfig.properties().readTimeoutMillis(), TimeUnit.MILLISECONDS)
+            .readTimeout(10, TimeUnit.MILLISECONDS)
```
Comment (tatu-at-datastax) [inline src/main/java/io/stargate/sgv2/jsonapi/service/reranking/operation/NvidiaRerankingProvider.java]: Is this change intentional? 10 msecs sounds bit low as default?

Comment (Hazel-Datastax) [reply src/main/java/io/stargate/sgv2/jsonapi/service/reranking/operation/NvidiaRerankingProvider.java]: Changed to reproduce and report a bug, forgot to change back:) Reverted this change
